/**
 * ILCA 6 Regatta Results Data for:
 * 1. Cincapura Regatta 2026 (ILCA 6) - 16 entries, 3 races, 0 discards (20–21 July 2026)
 * 2. Pesta Sukan Regatta 2026 (ILCA 6) - 21 entries, 5 races, 1 discard (1–3 August 2026)
 * 3. Singapore National Sailing Championships 2026 (ILCA 6) - 19 entries, 9 races, 1 discard (11–15 September 2026)
 *
 * Source: Official Singapore Sailing Federation Sailwave scoring sheets.
 */

import type { RegattaRecord, SailorRecord, RegattaResultRecord } from "@/lib/ranking";

export interface Ilca6RaceScore {
  raceNumber: number;
  score: number;
  rawValue: string;
  scoringCode?: string | null;
  discarded?: boolean;
}

export interface Ilca6CompetitorResult {
  rank: number;
  sailorName: string;
  sailNumber: string;
  yearOfBirth?: number | null;
  ageCategory?: string | null;
  novice?: boolean;
  gender: "M" | "F";
  schoolName?: string | null;
  club: string;
  nationality?: string | null;
  totalScore: number;
  nettScore: number;
  isDns?: boolean;
  races: Ilca6RaceScore[];
}

export const CINCAPURA_2026_ILCA6_RESULTS: Ilca6CompetitorResult[] = [
  {
    rank: 1,
    sailorName: "Sarah Rui-En Yong",
    sailNumber: "221689",
    gender: "F",
    schoolName: "Nanyang Polytechnic",
    club: "Royal Varuna Yacht Club",
    nationality: "SGP",
    totalScore: 6,
    nettScore: 6,
    races: [
      { raceNumber: 1, score: 2, rawValue: "2" },
      { raceNumber: 2, score: 2, rawValue: "2" },
      { raceNumber: 3, score: 2, rawValue: "2" },
    ],
  },
  {
    rank: 2,
    sailorName: "Keira Carlyle",
    sailNumber: "225225",
    gender: "F",
    schoolName: "Nanyang Polytechnic",
    club: "SAF Yacht Club",
    nationality: "SGP",
    totalScore: 7,
    nettScore: 7,
    races: [
      { raceNumber: 1, score: 3, rawValue: "3" },
      { raceNumber: 2, score: 1, rawValue: "1" },
      { raceNumber: 3, score: 3, rawValue: "3" },
    ],
  },
  {
    rank: 3,
    sailorName: "Kenan Kee Zen Tan",
    sailNumber: "1",
    gender: "M",
    club: "Royal Varuna Yacht Club",
    nationality: "SGP",
    totalScore: 9,
    nettScore: 9,
    races: [
      { raceNumber: 1, score: 5, rawValue: "5" },
      { raceNumber: 2, score: 3, rawValue: "3" },
      { raceNumber: 3, score: 1, rawValue: "1" },
    ],
  },
  {
    rank: 4,
    sailorName: "Nia Zahedi",
    sailNumber: "224245",
    gender: "F",
    schoolName: "Raffles Institution",
    club: "PAssion Wave",
    nationality: "SGP",
    totalScore: 12,
    nettScore: 12,
    races: [
      { raceNumber: 1, score: 1, rawValue: "1" },
      { raceNumber: 2, score: 6, rawValue: "6" },
      { raceNumber: 3, score: 5, rawValue: "5" },
    ],
  },
  {
    rank: 5,
    sailorName: "Gabi Oh",
    sailNumber: "224717",
    gender: "F",
    schoolName: "Raffles Institution",
    club: "SAF Yacht Club",
    nationality: "SGP",
    totalScore: 19,
    nettScore: 19,
    races: [
      { raceNumber: 1, score: 6, rawValue: "6" },
      { raceNumber: 2, score: 7, rawValue: "7" },
      { raceNumber: 3, score: 6, rawValue: "6" },
    ],
  },
  {
    rank: 6,
    sailorName: "Kai Lun Wong",
    sailNumber: "227462",
    ageCategory: "15&U",
    gender: "M",
    schoolName: "Bowen Secondary School",
    club: "PAssion Wave",
    nationality: "SGP",
    totalScore: 21,
    nettScore: 21,
    races: [
      { raceNumber: 1, score: 7, rawValue: "7" },
      { raceNumber: 2, score: 5, rawValue: "5" },
      { raceNumber: 3, score: 9, rawValue: "9" },
    ],
  },
  {
    rank: 7,
    sailorName: "Jayden Teo",
    sailNumber: "228158",
    gender: "M",
    schoolName: "St. Joseph's Institution",
    club: "PAssion Wave",
    nationality: "SGP",
    totalScore: 23,
    nettScore: 23,
    races: [
      { raceNumber: 1, score: 9, rawValue: "9" },
      { raceNumber: 2, score: 4, rawValue: "4" },
      { raceNumber: 3, score: 10, rawValue: "10" },
    ],
  },
  {
    rank: 8,
    sailorName: "Gordon Alexander Allan",
    sailNumber: "221058",
    gender: "M",
    schoolName: "Anglo-Chinese School (Independent)",
    club: "Royal Varuna Yacht Club",
    nationality: "SGP",
    totalScore: 25,
    nettScore: 25,
    races: [
      { raceNumber: 1, score: 10, rawValue: "10" },
      { raceNumber: 2, score: 8, rawValue: "8" },
      { raceNumber: 3, score: 7, rawValue: "7" },
    ],
  },
  {
    rank: 9,
    sailorName: "Cleo En Rui Seah",
    sailNumber: "224379",
    gender: "F",
    schoolName: "Ngee Ann Polytechnic",
    club: "SAF Yacht Club",
    nationality: "SGP",
    totalScore: 26,
    nettScore: 26,
    races: [
      { raceNumber: 1, score: 4, rawValue: "4" },
      { raceNumber: 2, score: 11, rawValue: "11" },
      { raceNumber: 3, score: 11, rawValue: "11" },
    ],
  },
  {
    rank: 10,
    sailorName: "Justiin Ang",
    sailNumber: "158031",
    gender: "M",
    club: "Constant Wind SeaSports",
    nationality: "SGP",
    totalScore: 27,
    nettScore: 27,
    races: [
      { raceNumber: 1, score: 11, rawValue: "11" },
      { raceNumber: 2, score: 12, rawValue: "12" },
      { raceNumber: 3, score: 4, rawValue: "4" },
    ],
  },
  {
    rank: 11,
    sailorName: "Yuei Jit Foo",
    sailNumber: "221686",
    gender: "M",
    schoolName: "Anderson Serangoon Junior College",
    club: "PAssion Wave",
    nationality: "SGP",
    totalScore: 30,
    nettScore: 30,
    races: [
      { raceNumber: 1, score: 13, rawValue: "13" },
      { raceNumber: 2, score: 9, rawValue: "9" },
      { raceNumber: 3, score: 8, rawValue: "8" },
    ],
  },
  {
    rank: 12,
    sailorName: "Travis Jia Le Yeo",
    sailNumber: "222727",
    ageCategory: "15&U",
    novice: true,
    gender: "M",
    schoolName: "Raffles Institution",
    club: "SAF Yacht Club",
    nationality: "SGP",
    totalScore: 30,
    nettScore: 30,
    races: [
      { raceNumber: 1, score: 8, rawValue: "8" },
      { raceNumber: 2, score: 10, rawValue: "10" },
      { raceNumber: 3, score: 12, rawValue: "12" },
    ],
  },
  {
    rank: 13,
    sailorName: "Sarfraz Ahmad Khan",
    sailNumber: "223871",
    gender: "M",
    club: "Constant Wind SeaSports",
    nationality: "SGP",
    totalScore: 40,
    nettScore: 40,
    races: [
      { raceNumber: 1, score: 12, rawValue: "12" },
      { raceNumber: 2, score: 14, rawValue: "14" },
      { raceNumber: 3, score: 14, rawValue: "14" },
    ],
  },
  {
    rank: 14,
    sailorName: "Darren Lai",
    sailNumber: "222257",
    ageCategory: "15&U",
    gender: "M",
    schoolName: "St. Joseph's Institution",
    club: "Royal Varuna Yacht Club",
    nationality: "SGP",
    totalScore: 40,
    nettScore: 40,
    races: [
      { raceNumber: 1, score: 14, rawValue: "14" },
      { raceNumber: 2, score: 13, rawValue: "13" },
      { raceNumber: 3, score: 13, rawValue: "13" },
    ],
  },
  {
    rank: 15,
    sailorName: "Rohit Behl",
    sailNumber: "221931",
    gender: "M",
    club: "Changi Sailing Club",
    nationality: "IND",
    totalScore: 47,
    nettScore: 47,
    races: [
      { raceNumber: 1, score: 15, rawValue: "15" },
      { raceNumber: 2, score: 17, rawValue: "17 NSC", scoringCode: "NSC" },
      { raceNumber: 3, score: 15, rawValue: "15" },
    ],
  },
  {
    rank: 16,
    sailorName: "Elizabeth Victoria Say",
    sailNumber: "214873",
    gender: "F",
    schoolName: "Dunman High School",
    club: "PAssion Wave",
    nationality: "SGP",
    totalScore: 51,
    nettScore: 51,
    races: [
      { raceNumber: 1, score: 17, rawValue: "17 SCP", scoringCode: "SCP" },
      { raceNumber: 2, score: 17, rawValue: "17 RET", scoringCode: "RET" },
      { raceNumber: 3, score: 17, rawValue: "17 RET", scoringCode: "RET" },
    ],
  },
];

export const PESTA_SUKAN_2026_ILCA6_RESULTS: Ilca6CompetitorResult[] = [
  {
    rank: 1,
    sailorName: "Kenan Kee Zen Tan",
    sailNumber: "1",
    gender: "M",
    club: "Royal Varuna Yacht Club",
    nationality: "SGP",
    totalScore: 11,
    nettScore: 7,
    races: [
      { raceNumber: 1, score: 1, rawValue: "1" },
      { raceNumber: 2, score: 4, rawValue: "(4)", discarded: true },
      { raceNumber: 3, score: 1, rawValue: "1" },
      { raceNumber: 4, score: 1, rawValue: "1" },
      { raceNumber: 5, score: 4, rawValue: "4" },
    ],
  },
  {
    rank: 2,
    sailorName: "Austin Jia Yu Yeo",
    sailNumber: "221062",
    gender: "M",
    schoolName: "Anglo-Chinese School (Independent)",
    club: "SAF Yacht Club",
    nationality: "SGP",
    totalScore: 12,
    nettScore: 7,
    races: [
      { raceNumber: 1, score: 2, rawValue: "2" },
      { raceNumber: 2, score: 1, rawValue: "1" },
      { raceNumber: 3, score: 2, rawValue: "2" },
      { raceNumber: 4, score: 2, rawValue: "2" },
      { raceNumber: 5, score: 5, rawValue: "(5)", discarded: true },
    ],
  },
  {
    rank: 3,
    sailorName: "Keira Carlyle",
    sailNumber: "225225",
    gender: "F",
    club: "SAF Yacht Club",
    nationality: "SGP",
    totalScore: 15,
    nettScore: 11,
    races: [
      { raceNumber: 1, score: 3, rawValue: "3" },
      { raceNumber: 2, score: 2, rawValue: "2" },
      { raceNumber: 3, score: 4, rawValue: "(4)", discarded: true },
      { raceNumber: 4, score: 4, rawValue: "4" },
      { raceNumber: 5, score: 2, rawValue: "2" },
    ],
  },
  {
    rank: 4,
    sailorName: "Nia Zahedi",
    sailNumber: "224245",
    gender: "F",
    schoolName: "Raffles Institution",
    club: "PAssion Wave",
    nationality: "SGP",
    totalScore: 23,
    nettScore: 15,
    races: [
      { raceNumber: 1, score: 4, rawValue: "4" },
      { raceNumber: 2, score: 5, rawValue: "5" },
      { raceNumber: 3, score: 3, rawValue: "3" },
      { raceNumber: 4, score: 8, rawValue: "(8)", discarded: true },
      { raceNumber: 5, score: 3, rawValue: "3" },
    ],
  },
  {
    rank: 5,
    sailorName: "Gordon Alexander Allan",
    sailNumber: "221058",
    gender: "M",
    schoolName: "Anglo-Chinese School (Independent)",
    club: "Royal Varuna Yacht Club",
    nationality: "SGP",
    totalScore: 34,
    nettScore: 22,
    races: [
      { raceNumber: 1, score: 11, rawValue: "11" },
      { raceNumber: 2, score: 3, rawValue: "3" },
      { raceNumber: 3, score: 5, rawValue: "5" },
      { raceNumber: 4, score: 3, rawValue: "3" },
      { raceNumber: 5, score: 12, rawValue: "(12)", discarded: true },
    ],
  },
  {
    rank: 6,
    sailorName: "Gabi Oh",
    sailNumber: "224717",
    gender: "F",
    schoolName: "Raffles Institution",
    club: "SAF Yacht Club",
    nationality: "SGP",
    totalScore: 35,
    nettScore: 25,
    races: [
      { raceNumber: 1, score: 6, rawValue: "6" },
      { raceNumber: 2, score: 8, rawValue: "8" },
      { raceNumber: 3, score: 6, rawValue: "6" },
      { raceNumber: 4, score: 5, rawValue: "5" },
      { raceNumber: 5, score: 10, rawValue: "(10)", discarded: true },
    ],
  },
  {
    rank: 7,
    sailorName: "Sarah Rui-En Yong",
    sailNumber: "222743",
    gender: "F",
    schoolName: "Nanyang Polytechnic",
    club: "Royal Varuna Yacht Club",
    nationality: "SGP",
    totalScore: 32,
    nettScore: 25,
    races: [
      { raceNumber: 1, score: 5, rawValue: "5" },
      { raceNumber: 2, score: 6, rawValue: "6" },
      { raceNumber: 3, score: 7, rawValue: "(7)", discarded: true },
      { raceNumber: 4, score: 7, rawValue: "7" },
      { raceNumber: 5, score: 7, rawValue: "7" },
    ],
  },
  {
    rank: 8,
    sailorName: "Kai Lun Wong",
    sailNumber: "227462",
    ageCategory: "15&U",
    gender: "M",
    schoolName: "Bowen Secondary School",
    club: "PAssion Wave",
    nationality: "SGP",
    totalScore: 38,
    nettScore: 29,
    races: [
      { raceNumber: 1, score: 9, rawValue: "(9)", discarded: true },
      { raceNumber: 2, score: 9, rawValue: "9" },
      { raceNumber: 3, score: 8, rawValue: "8" },
      { raceNumber: 4, score: 6, rawValue: "6" },
      { raceNumber: 5, score: 6, rawValue: "6" },
    ],
  },
  {
    rank: 9,
    sailorName: "Charlotte Wee Shuen Lee",
    sailNumber: "214235",
    gender: "F",
    club: "Royal Varuna Yacht Club",
    nationality: "SGP",
    totalScore: 43,
    nettScore: 31,
    races: [
      { raceNumber: 1, score: 8, rawValue: "8" },
      { raceNumber: 2, score: 11, rawValue: "11" },
      { raceNumber: 3, score: 12, rawValue: "(12)", discarded: true },
      { raceNumber: 4, score: 11, rawValue: "11" },
      { raceNumber: 5, score: 1, rawValue: "1" },
    ],
  },
  {
    rank: 10,
    sailorName: "Jayden Teo",
    sailNumber: "228158",
    gender: "M",
    schoolName: "St. Joseph's Institution",
    club: "PAssion Wave",
    nationality: "SGP",
    totalScore: 44,
    nettScore: 34,
    races: [
      { raceNumber: 1, score: 7, rawValue: "7" },
      { raceNumber: 2, score: 10, rawValue: "(10)", discarded: true },
      { raceNumber: 3, score: 9, rawValue: "9" },
      { raceNumber: 4, score: 10, rawValue: "10" },
      { raceNumber: 5, score: 8, rawValue: "8" },
    ],
  },
  {
    rank: 11,
    sailorName: "Yuei Jit Foo",
    sailNumber: "221686",
    gender: "M",
    schoolName: "Anderson Serangoon Junior College",
    club: "PAssion Wave",
    nationality: "SGP",
    totalScore: 50,
    nettScore: 37,
    races: [
      { raceNumber: 1, score: 10, rawValue: "10" },
      { raceNumber: 2, score: 7, rawValue: "7" },
      { raceNumber: 3, score: 11, rawValue: "11" },
      { raceNumber: 4, score: 9, rawValue: "9" },
      { raceNumber: 5, score: 13, rawValue: "(13)", discarded: true },
    ],
  },
  {
    rank: 12,
    sailorName: "Darren Lai",
    sailNumber: "222257",
    ageCategory: "15&U",
    gender: "M",
    schoolName: "St. Joseph's Institution",
    club: "Royal Varuna Yacht Club",
    nationality: "SGP",
    totalScore: 63,
    nettScore: 47,
    races: [
      { raceNumber: 1, score: 13, rawValue: "13" },
      { raceNumber: 2, score: 12, rawValue: "12" },
      { raceNumber: 3, score: 10, rawValue: "10" },
      { raceNumber: 4, score: 12, rawValue: "12" },
      { raceNumber: 5, score: 16, rawValue: "(16)", discarded: true },
    ],
  },
  {
    rank: 13,
    sailorName: "Darius Xian Rui Low",
    sailNumber: "8",
    gender: "M",
    schoolName: "St. Joseph's Institution",
    club: "PAssion Wave",
    nationality: "SGP",
    totalScore: 67,
    nettScore: 52,
    races: [
      { raceNumber: 1, score: 15, rawValue: "(15)", discarded: true },
      { raceNumber: 2, score: 15, rawValue: "15" },
      { raceNumber: 3, score: 14, rawValue: "14" },
      { raceNumber: 4, score: 14, rawValue: "14" },
      { raceNumber: 5, score: 9, rawValue: "9" },
    ],
  },
  {
    rank: 14,
    sailorName: "Cleo En Rui Seah",
    sailNumber: "224379",
    gender: "F",
    schoolName: "Ngee Ann Polytechnic",
    club: "SAF Yacht Club",
    nationality: "SGP",
    totalScore: 68,
    nettScore: 52,
    races: [
      { raceNumber: 1, score: 12, rawValue: "12" },
      { raceNumber: 2, score: 14, rawValue: "14" },
      { raceNumber: 3, score: 16, rawValue: "(16)", discarded: true },
      { raceNumber: 4, score: 15, rawValue: "15" },
      { raceNumber: 5, score: 11, rawValue: "11" },
    ],
  },
  {
    rank: 15,
    sailorName: "Rohit Behl",
    sailNumber: "221931",
    gender: "M",
    club: "Changi Sailing Club",
    nationality: "IND",
    totalScore: 74,
    nettScore: 56,
    races: [
      { raceNumber: 1, score: 14, rawValue: "14" },
      { raceNumber: 2, score: 13, rawValue: "13" },
      { raceNumber: 3, score: 13, rawValue: "13" },
      { raceNumber: 4, score: 16, rawValue: "16" },
      { raceNumber: 5, score: 18, rawValue: "(18)", discarded: true },
    ],
  },
  {
    rank: 16,
    sailorName: "Elizabeth Victoria Say",
    sailNumber: "214873",
    gender: "F",
    schoolName: "Dunman High School",
    club: "PAssion Wave",
    nationality: "SGP",
    totalScore: 75,
    nettScore: 59,
    races: [
      { raceNumber: 1, score: 16, rawValue: "(16)", discarded: true },
      { raceNumber: 2, score: 16, rawValue: "16" },
      { raceNumber: 3, score: 15, rawValue: "15" },
      { raceNumber: 4, score: 13, rawValue: "13" },
      { raceNumber: 5, score: 15, rawValue: "15" },
    ],
  },
  {
    rank: 17,
    sailorName: "Tiffany Teo",
    sailNumber: "214813",
    ageCategory: "15&U",
    novice: true,
    gender: "F",
    schoolName: "Bedok South Secondary School",
    club: "PAssion Wave",
    nationality: "SGP",
    totalScore: 85,
    nettScore: 66,
    races: [
      { raceNumber: 1, score: 19, rawValue: "(19)", discarded: true },
      { raceNumber: 2, score: 17, rawValue: "17" },
      { raceNumber: 3, score: 18, rawValue: "18" },
      { raceNumber: 4, score: 17, rawValue: "17" },
      { raceNumber: 5, score: 14, rawValue: "14" },
    ],
  },
  {
    rank: 18,
    sailorName: "Travis Jia Le Yeo",
    sailNumber: "222727",
    ageCategory: "15&U",
    gender: "M",
    schoolName: "Raffles Institution",
    club: "SAF Yacht Club",
    nationality: "SGP",
    totalScore: 93,
    nettScore: 71,
    races: [
      { raceNumber: 1, score: 17, rawValue: "17" },
      { raceNumber: 2, score: 19, rawValue: "19" },
      { raceNumber: 3, score: 17, rawValue: "17" },
      { raceNumber: 4, score: 18, rawValue: "18" },
      { raceNumber: 5, score: 22, rawValue: "(22 DNC)", scoringCode: "DNC", discarded: true },
    ],
  },
  {
    rank: 19,
    sailorName: "Sarfraz Ahmad Khan",
    sailNumber: "193871",
    gender: "M",
    club: "Constant Wind SeaSports",
    nationality: "SGP",
    totalScore: 91,
    nettScore: 72,
    races: [
      { raceNumber: 1, score: 18, rawValue: "18" },
      { raceNumber: 2, score: 18, rawValue: "18" },
      { raceNumber: 3, score: 19, rawValue: "(19)", discarded: true },
      { raceNumber: 4, score: 19, rawValue: "19" },
      { raceNumber: 5, score: 17, rawValue: "17" },
    ],
  },
  {
    rank: 20,
    sailorName: "Justiin Ang",
    sailNumber: "158031",
    gender: "M",
    schoolName: "Rosyth School",
    club: "Constant Wind SeaSports",
    nationality: "SGP",
    totalScore: 110,
    nettScore: 88,
    isDns: true,
    races: [
      { raceNumber: 1, score: 22, rawValue: "(22 DNC)", scoringCode: "DNC", discarded: true },
      { raceNumber: 2, score: 22, rawValue: "22 DNC", scoringCode: "DNC" },
      { raceNumber: 3, score: 22, rawValue: "22 DNC", scoringCode: "DNC" },
      { raceNumber: 4, score: 22, rawValue: "22 DNC", scoringCode: "DNC" },
      { raceNumber: 5, score: 22, rawValue: "22 DNC", scoringCode: "DNC" },
    ],
  },
  {
    rank: 20,
    sailorName: "Bryan Chan",
    sailNumber: "197850",
    novice: true,
    gender: "M",
    club: "SAF Yacht Club",
    nationality: "SGP",
    totalScore: 110,
    nettScore: 88,
    races: [
      { raceNumber: 1, score: 22, rawValue: "(22 DNF)", scoringCode: "DNF", discarded: true },
      { raceNumber: 2, score: 22, rawValue: "22 RET", scoringCode: "RET" },
      { raceNumber: 3, score: 22, rawValue: "22 DNF", scoringCode: "DNF" },
      { raceNumber: 4, score: 22, rawValue: "22 RET", scoringCode: "RET" },
      { raceNumber: 5, score: 22, rawValue: "22 DNF", scoringCode: "DNF" },
    ],
  },
];

export const SNSC_2026_ILCA6_RESULTS: Ilca6CompetitorResult[] = [
  {
    rank: 1,
    sailorName: "Kenan Kee Zen Tan",
    sailNumber: "221060",
    gender: "M",
    club: "Royal Varuna Yacht Club",
    nationality: "SGP",
    totalScore: 23,
    nettScore: 15,
    races: [
      { raceNumber: 1, score: 1, rawValue: "1" },
      { raceNumber: 2, score: 1, rawValue: "1" },
      { raceNumber: 3, score: 2, rawValue: "2" },
      { raceNumber: 4, score: 8, rawValue: "(8)", discarded: true },
      { raceNumber: 5, score: 1, rawValue: "1" },
      { raceNumber: 6, score: 1, rawValue: "1" },
      { raceNumber: 7, score: 1, rawValue: "1" },
      { raceNumber: 8, score: 1, rawValue: "1" },
      { raceNumber: 9, score: 7, rawValue: "7" },
    ],
  },
  {
    rank: 2,
    sailorName: "Keira Carlyle",
    sailNumber: "225225",
    gender: "F",
    club: "SAF Yacht Club",
    nationality: "SGP",
    totalScore: 33,
    nettScore: 23,
    races: [
      { raceNumber: 1, score: 2, rawValue: "2" },
      { raceNumber: 2, score: 3, rawValue: "3" },
      { raceNumber: 3, score: 4, rawValue: "4" },
      { raceNumber: 4, score: 1, rawValue: "1" },
      { raceNumber: 5, score: 2, rawValue: "2" },
      { raceNumber: 6, score: 3, rawValue: "3" },
      { raceNumber: 7, score: 4, rawValue: "4" },
      { raceNumber: 8, score: 10, rawValue: "(10)", discarded: true },
      { raceNumber: 9, score: 4, rawValue: "4" },
    ],
  },
  {
    rank: 3,
    sailorName: "Sarah Rui-En Yong",
    sailNumber: "221689",
    gender: "F",
    schoolName: "Nanyang Polytechnic",
    club: "Royal Varuna Yacht Club",
    nationality: "SGP",
    totalScore: 40,
    nettScore: 29,
    races: [
      { raceNumber: 1, score: 4, rawValue: "4" },
      { raceNumber: 2, score: 9, rawValue: "9" },
      { raceNumber: 3, score: 1, rawValue: "1" },
      { raceNumber: 4, score: 3, rawValue: "3" },
      { raceNumber: 5, score: 3, rawValue: "3" },
      { raceNumber: 6, score: 2, rawValue: "2" },
      { raceNumber: 7, score: 6, rawValue: "6" },
      { raceNumber: 8, score: 11, rawValue: "(11)", discarded: true },
      { raceNumber: 9, score: 1, rawValue: "1" },
    ],
  },
  {
    rank: 4,
    sailorName: "Austin Jia Yu Yeo",
    sailNumber: "221062",
    gender: "M",
    schoolName: "Anglo-Chinese School (Independent)",
    club: "SAF Yacht Club",
    nationality: "SGP",
    totalScore: 49,
    nettScore: 37,
    races: [
      { raceNumber: 1, score: 11, rawValue: "11" },
      { raceNumber: 2, score: 2, rawValue: "2" },
      { raceNumber: 3, score: 5, rawValue: "5" },
      { raceNumber: 4, score: 6, rawValue: "6" },
      { raceNumber: 5, score: 12, rawValue: "(12)", discarded: true },
      { raceNumber: 6, score: 4, rawValue: "4" },
      { raceNumber: 7, score: 2, rawValue: "2" },
      { raceNumber: 8, score: 4, rawValue: "4" },
      { raceNumber: 9, score: 3, rawValue: "3" },
    ],
  },
  {
    rank: 5,
    sailorName: "Nia Zahedi",
    sailNumber: "224245",
    gender: "F",
    schoolName: "Raffles Institution",
    club: "PAssion Wave",
    nationality: "SGP",
    totalScore: 62,
    nettScore: 42,
    races: [
      { raceNumber: 1, score: 3, rawValue: "3" },
      { raceNumber: 2, score: 11, rawValue: "11" },
      { raceNumber: 3, score: 6, rawValue: "6" },
      { raceNumber: 4, score: 2, rawValue: "2" },
      { raceNumber: 5, score: 8, rawValue: "8" },
      { raceNumber: 6, score: 7, rawValue: "7" },
      { raceNumber: 7, score: 3, rawValue: "3" },
      { raceNumber: 8, score: 20, rawValue: "(20 UFD)", scoringCode: "UFD", discarded: true },
      { raceNumber: 9, score: 2, rawValue: "2" },
    ],
  },
  {
    rank: 6,
    sailorName: "Misa Lim Laurie",
    sailNumber: "223202",
    ageCategory: "15&U",
    novice: true,
    gender: "F",
    schoolName: "Singapore American School",
    club: "Changi Sailing Club",
    nationality: "USA",
    totalScore: 63,
    nettScore: 52,
    races: [
      { raceNumber: 1, score: 5, rawValue: "5" },
      { raceNumber: 2, score: 6, rawValue: "6" },
      { raceNumber: 3, score: 10, rawValue: "10" },
      { raceNumber: 4, score: 4, rawValue: "4" },
      { raceNumber: 5, score: 6, rawValue: "6" },
      { raceNumber: 6, score: 6, rawValue: "6" },
      { raceNumber: 7, score: 10, rawValue: "10" },
      { raceNumber: 8, score: 5, rawValue: "5" },
      { raceNumber: 9, score: 11, rawValue: "(11)", discarded: true },
    ],
  },
  {
    rank: 7,
    sailorName: "Gabi Oh",
    sailNumber: "224717",
    gender: "F",
    schoolName: "Raffles Institution",
    club: "SAF Yacht Club",
    nationality: "SGP",
    totalScore: 69,
    nettScore: 57,
    races: [
      { raceNumber: 1, score: 12, rawValue: "(12)", discarded: true },
      { raceNumber: 2, score: 5, rawValue: "5" },
      { raceNumber: 3, score: 7, rawValue: "7" },
      { raceNumber: 4, score: 9, rawValue: "9" },
      { raceNumber: 5, score: 4, rawValue: "4" },
      { raceNumber: 6, score: 12, rawValue: "12" },
      { raceNumber: 7, score: 8, rawValue: "8" },
      { raceNumber: 8, score: 7, rawValue: "7" },
      { raceNumber: 9, score: 5, rawValue: "5" },
    ],
  },
  {
    rank: 8,
    sailorName: "Gordon Alexander Allan",
    sailNumber: "221058",
    gender: "M",
    schoolName: "Anglo-Chinese School (Independent)",
    club: "Royal Varuna Yacht Club",
    nationality: "SGP",
    totalScore: 79,
    nettScore: 64,
    races: [
      { raceNumber: 1, score: 9, rawValue: "9" },
      { raceNumber: 2, score: 4, rawValue: "4" },
      { raceNumber: 3, score: 9, rawValue: "9" },
      { raceNumber: 4, score: 15, rawValue: "(15)", discarded: true },
      { raceNumber: 5, score: 11, rawValue: "11" },
      { raceNumber: 6, score: 11, rawValue: "11" },
      { raceNumber: 7, score: 7, rawValue: "7" },
      { raceNumber: 8, score: 3, rawValue: "3" },
      { raceNumber: 9, score: 10, rawValue: "10" },
    ],
  },
  {
    rank: 9,
    sailorName: "Jayden Teo",
    sailNumber: "228158",
    gender: "M",
    schoolName: "St. Joseph's Institution",
    club: "PAssion Wave",
    nationality: "SGP",
    totalScore: 85,
    nettScore: 71,
    races: [
      { raceNumber: 1, score: 10, rawValue: "10" },
      { raceNumber: 2, score: 13, rawValue: "13" },
      { raceNumber: 3, score: 11, rawValue: "11" },
      { raceNumber: 4, score: 13, rawValue: "13" },
      { raceNumber: 5, score: 5, rawValue: "5" },
      { raceNumber: 6, score: 8, rawValue: "8" },
      { raceNumber: 7, score: 5, rawValue: "5" },
      { raceNumber: 8, score: 6, rawValue: "6" },
      { raceNumber: 9, score: 14, rawValue: "(14)", discarded: true },
    ],
  },
  {
    rank: 10,
    sailorName: "Justiin Ang",
    sailNumber: "158031",
    gender: "M",
    club: "Constant Wind SeaSports",
    nationality: "SGP",
    totalScore: 91,
    nettScore: 71,
    races: [
      { raceNumber: 1, score: 20, rawValue: "(20 DNC)", scoringCode: "DNC", discarded: true },
      { raceNumber: 2, score: 20, rawValue: "20 DNC", scoringCode: "DNC" },
      { raceNumber: 3, score: 8, rawValue: "8" },
      { raceNumber: 4, score: 5, rawValue: "5" },
      { raceNumber: 5, score: 7, rawValue: "7" },
      { raceNumber: 6, score: 5, rawValue: "5" },
      { raceNumber: 7, score: 9, rawValue: "9" },
      { raceNumber: 8, score: 8, rawValue: "8 DPI", scoringCode: "DPI" },
      { raceNumber: 9, score: 9, rawValue: "9" },
    ],
  },
  {
    rank: 11,
    sailorName: "Kai Lun Wong",
    sailNumber: "227462",
    ageCategory: "15&U",
    gender: "M",
    schoolName: "Bowen Secondary School",
    club: "PAssion Wave",
    nationality: "SGP",
    totalScore: 84,
    nettScore: 72,
    races: [
      { raceNumber: 1, score: 7, rawValue: "7" },
      { raceNumber: 2, score: 7, rawValue: "7" },
      { raceNumber: 3, score: 12, rawValue: "(12)", discarded: true },
      { raceNumber: 4, score: 11, rawValue: "11" },
      { raceNumber: 5, score: 10, rawValue: "10" },
      { raceNumber: 6, score: 10, rawValue: "10" },
      { raceNumber: 7, score: 11, rawValue: "11" },
      { raceNumber: 8, score: 8, rawValue: "8" },
      { raceNumber: 9, score: 8, rawValue: "8" },
    ],
  },
  {
    rank: 12,
    sailorName: "Cleo En Rui Seah",
    sailNumber: "224379",
    gender: "F",
    schoolName: "Ngee Ann Polytechnic",
    club: "SAF Yacht Club",
    nationality: "SGP",
    totalScore: 88,
    nettScore: 75,
    races: [
      { raceNumber: 1, score: 6, rawValue: "6" },
      { raceNumber: 2, score: 10, rawValue: "10" },
      { raceNumber: 3, score: 13, rawValue: "(13)", discarded: true },
      { raceNumber: 4, score: 10, rawValue: "10" },
      { raceNumber: 5, score: 9, rawValue: "9" },
      { raceNumber: 6, score: 9, rawValue: "9" },
      { raceNumber: 7, score: 13, rawValue: "13" },
      { raceNumber: 8, score: 12, rawValue: "12" },
      { raceNumber: 9, score: 6, rawValue: "6" },
    ],
  },
  {
    rank: 13,
    sailorName: "Darren Lai",
    sailNumber: "222257",
    ageCategory: "15&U",
    gender: "M",
    schoolName: "St. Joseph's Institution",
    club: "Royal Varuna Yacht Club",
    nationality: "SGP",
    totalScore: 113,
    nettScore: 97,
    races: [
      { raceNumber: 1, score: 8, rawValue: "8" },
      { raceNumber: 2, score: 8, rawValue: "8" },
      { raceNumber: 3, score: 16, rawValue: "(16)", discarded: true },
      { raceNumber: 4, score: 12, rawValue: "12" },
      { raceNumber: 5, score: 14, rawValue: "14" },
      { raceNumber: 6, score: 16, rawValue: "16" },
      { raceNumber: 7, score: 15, rawValue: "15" },
      { raceNumber: 8, score: 9, rawValue: "9" },
      { raceNumber: 9, score: 15, rawValue: "15" },
    ],
  },
  {
    rank: 14,
    sailorName: "Tiffany Teo",
    sailNumber: "214813",
    ageCategory: "15&U",
    gender: "F",
    schoolName: "Bedok South Secondary School",
    club: "PAssion Wave",
    nationality: "SGP",
    totalScore: 129,
    nettScore: 112,
    races: [
      { raceNumber: 1, score: 13, rawValue: "13" },
      { raceNumber: 2, score: 15, rawValue: "15" },
      { raceNumber: 3, score: 15, rawValue: "15" },
      { raceNumber: 4, score: 17, rawValue: "(17)", discarded: true },
      { raceNumber: 5, score: 13, rawValue: "13" },
      { raceNumber: 6, score: 13, rawValue: "13" },
      { raceNumber: 7, score: 16, rawValue: "16" },
      { raceNumber: 8, score: 15, rawValue: "15" },
      { raceNumber: 9, score: 12, rawValue: "12" },
    ],
  },
  {
    rank: 15,
    sailorName: "Travis Jia Le Yeo",
    sailNumber: "222727",
    ageCategory: "15&U",
    gender: "M",
    schoolName: "Raffles Institution",
    club: "SAF Yacht Club",
    nationality: "SGP",
    totalScore: 130,
    nettScore: 113,
    races: [
      { raceNumber: 1, score: 15, rawValue: "15" },
      { raceNumber: 2, score: 12, rawValue: "12" },
      { raceNumber: 3, score: 17, rawValue: "(17)", discarded: true },
      { raceNumber: 4, score: 16, rawValue: "16" },
      { raceNumber: 5, score: 16, rawValue: "16" },
      { raceNumber: 6, score: 14, rawValue: "14" },
      { raceNumber: 7, score: 14, rawValue: "14" },
      { raceNumber: 8, score: 13, rawValue: "13" },
      { raceNumber: 9, score: 13, rawValue: "13" },
    ],
  },
  {
    rank: 16,
    sailorName: "Rohit Behl",
    sailNumber: "221931",
    gender: "M",
    club: "Changi Sailing Club",
    nationality: "IND",
    totalScore: 141,
    nettScore: 121,
    races: [
      { raceNumber: 1, score: 14, rawValue: "14" },
      { raceNumber: 2, score: 14, rawValue: "14" },
      { raceNumber: 3, score: 14, rawValue: "14" },
      { raceNumber: 4, score: 14, rawValue: "14" },
      { raceNumber: 5, score: 17, rawValue: "17" },
      { raceNumber: 6, score: 20, rawValue: "(20 RET)", scoringCode: "RET", discarded: true },
      { raceNumber: 7, score: 12, rawValue: "12" },
      { raceNumber: 8, score: 20, rawValue: "20 UFD", scoringCode: "UFD" },
      { raceNumber: 9, score: 16, rawValue: "16" },
    ],
  },
  {
    rank: 17,
    sailorName: "Lucien Franciscus Henricus van Riel",
    sailNumber: "207763",
    gender: "M",
    club: "Constant Wind SeaSports",
    nationality: "NED",
    totalScore: 146,
    nettScore: 128,
    races: [
      { raceNumber: 1, score: 16, rawValue: "16" },
      { raceNumber: 2, score: 16, rawValue: "16" },
      { raceNumber: 3, score: 18, rawValue: "(18)", discarded: true },
      { raceNumber: 4, score: 18, rawValue: "18" },
      { raceNumber: 5, score: 15, rawValue: "15" },
      { raceNumber: 6, score: 15, rawValue: "15" },
      { raceNumber: 7, score: 17, rawValue: "17" },
      { raceNumber: 8, score: 14, rawValue: "14" },
      { raceNumber: 9, score: 17, rawValue: "17" },
    ],
  },
  {
    rank: 18,
    sailorName: "Maia Lim Laurie",
    sailNumber: "223201",
    gender: "F",
    schoolName: "Singapore American School",
    club: "Changi Sailing Club",
    nationality: "USA",
    totalScore: 150,
    nettScore: 130,
    races: [
      { raceNumber: 1, score: 20, rawValue: "(20 DNC)", scoringCode: "DNC", discarded: true },
      { raceNumber: 2, score: 20, rawValue: "20 DNC", scoringCode: "DNC" },
      { raceNumber: 3, score: 3, rawValue: "3" },
      { raceNumber: 4, score: 7, rawValue: "7" },
      { raceNumber: 5, score: 20, rawValue: "20 RET", scoringCode: "RET" },
      { raceNumber: 6, score: 20, rawValue: "20 DNS", scoringCode: "DNS" },
      { raceNumber: 7, score: 20, rawValue: "20 DNC", scoringCode: "DNC" },
      { raceNumber: 8, score: 20, rawValue: "20 DNC", scoringCode: "DNC" },
      { raceNumber: 9, score: 20, rawValue: "20 DNC", scoringCode: "DNC" },
    ],
  },
  {
    rank: 19,
    sailorName: "Elizabeth Victoria Say",
    sailNumber: "214873",
    gender: "F",
    schoolName: "Dunman High School",
    club: "PAssion Wave",
    nationality: "SGP",
    totalScore: 180,
    nettScore: 160,
    isDns: true,
    races: [
      { raceNumber: 1, score: 20, rawValue: "(20 DNC)", scoringCode: "DNC", discarded: true },
      { raceNumber: 2, score: 20, rawValue: "20 DNC", scoringCode: "DNC" },
      { raceNumber: 3, score: 20, rawValue: "20 DNC", scoringCode: "DNC" },
      { raceNumber: 4, score: 20, rawValue: "20 DNC", scoringCode: "DNC" },
      { raceNumber: 5, score: 20, rawValue: "20 DNC", scoringCode: "DNC" },
      { raceNumber: 6, score: 20, rawValue: "20 DNC", scoringCode: "DNC" },
      { raceNumber: 7, score: 20, rawValue: "20 DNC", scoringCode: "DNC" },
      { raceNumber: 8, score: 20, rawValue: "20 DNC", scoringCode: "DNC" },
      { raceNumber: 9, score: 20, rawValue: "20 DNC", scoringCode: "DNC" },
    ],
  },
];

export const PULAU_UJONG_2026_ILCA6_RESULTS: Ilca6CompetitorResult[] = [
  {
    rank: 1,
    sailorName: "Kenan Kee Zen Tan",
    sailNumber: "1",
    gender: "M",
    club: "Royal Varuna Yacht Club",
    nationality: "SGP",
    yearOfBirth: 2007,
    totalScore: 7,
    nettScore: 5,
    races: [
      { raceNumber: 1, score: 1, rawValue: "1" },
      { raceNumber: 2, score: 1, rawValue: "1" },
      { raceNumber: 3, score: 1, rawValue: "1" },
      { raceNumber: 4, score: 1, rawValue: "1" },
      { raceNumber: 5, score: 1, rawValue: "1" },
      { raceNumber: 6, score: 2, rawValue: "2", discarded: true },
    ],
  },
  {
    rank: 2,
    sailorName: "Gordon Alexander Allan",
    sailNumber: "221058",
    gender: "M",
    schoolName: "Anglo-Chinese School (Independent)",
    club: "Royal Varuna Yacht Club",
    nationality: "SGP",
    yearOfBirth: 2010,
    totalScore: 27,
    nettScore: 17,
    races: [
      { raceNumber: 1, score: 5, rawValue: "5" },
      { raceNumber: 2, score: 5, rawValue: "5" },
      { raceNumber: 3, score: 2, rawValue: "2" },
      { raceNumber: 4, score: 2, rawValue: "2" },
      { raceNumber: 5, score: 10, rawValue: "10", discarded: true },
      { raceNumber: 6, score: 3, rawValue: "3" },
    ],
  },
  {
    rank: 3,
    sailorName: "Eitan Oh",
    sailNumber: "224717",
    gender: "M",
    schoolName: "Raffles Institution",
    club: "SAF Yacht Club",
    nationality: "SGP",
    yearOfBirth: 2008,
    totalScore: 23,
    nettScore: 17,
    races: [
      { raceNumber: 1, score: 2, rawValue: "2" },
      { raceNumber: 2, score: 2, rawValue: "2" },
      { raceNumber: 3, score: 3, rawValue: "3" },
      { raceNumber: 4, score: 5, rawValue: "5" },
      { raceNumber: 5, score: 6, rawValue: "6", discarded: true },
      { raceNumber: 6, score: 5, rawValue: "5" },
    ],
  },
  {
    rank: 4,
    sailorName: "Justiin Ang",
    sailNumber: "158031",
    gender: "M",
    club: "Constant Wind SeaSports",
    nationality: "SGP",
    yearOfBirth: 1979,
    totalScore: 39,
    nettScore: 22,
    races: [
      { raceNumber: 1, score: 4, rawValue: "4" },
      { raceNumber: 2, score: 3, rawValue: "3" },
      { raceNumber: 3, score: 7, rawValue: "7" },
      { raceNumber: 4, score: 3, rawValue: "3" },
      { raceNumber: 5, score: 5, rawValue: "5" },
      { raceNumber: 6, score: 17, rawValue: "17 RET", scoringCode: "RET", discarded: true },
    ],
  },
  {
    rank: 5,
    sailorName: "Sarah Rui-En Yong",
    sailNumber: "221689",
    gender: "F",
    schoolName: "Nanyang Polytechnic",
    club: "Royal Varuna Yacht Club",
    nationality: "SGP",
    yearOfBirth: 2008,
    totalScore: 42,
    nettScore: 30,
    races: [
      { raceNumber: 1, score: 6, rawValue: "6" },
      { raceNumber: 2, score: 7, rawValue: "7" },
      { raceNumber: 3, score: 10, rawValue: "10" },
      { raceNumber: 4, score: 12, rawValue: "12", discarded: true },
      { raceNumber: 5, score: 3, rawValue: "3" },
      { raceNumber: 6, score: 4, rawValue: "4" },
    ],
  },
  {
    rank: 6,
    sailorName: "Keira Carlyle",
    sailNumber: "25",
    gender: "F",
    schoolName: "Nanyang Polytechnic",
    club: "SAF Yacht Club",
    nationality: "SGP",
    yearOfBirth: 2006,
    totalScore: 44,
    nettScore: 31,
    races: [
      { raceNumber: 1, score: 13, rawValue: "13", discarded: true },
      { raceNumber: 2, score: 8, rawValue: "8" },
      { raceNumber: 3, score: 4, rawValue: "4" },
      { raceNumber: 4, score: 9, rawValue: "9" },
      { raceNumber: 5, score: 4, rawValue: "4" },
      { raceNumber: 6, score: 6, rawValue: "6" },
    ],
  },
  {
    rank: 7,
    sailorName: "Austin Jia Yu Yeo",
    sailNumber: "2",
    gender: "M",
    schoolName: "Anglo-Chinese School (Independent)",
    club: "SAF Yacht Club",
    nationality: "SGP",
    yearOfBirth: 2009,
    totalScore: 49,
    nettScore: 32,
    races: [
      { raceNumber: 1, score: 7, rawValue: "7" },
      { raceNumber: 2, score: 17, rawValue: "17 DNF", scoringCode: "DNF", discarded: true },
      { raceNumber: 3, score: 5, rawValue: "5" },
      { raceNumber: 4, score: 17, rawValue: "17 DNF", scoringCode: "DNF" },
      { raceNumber: 5, score: 2, rawValue: "2" },
      { raceNumber: 6, score: 1, rawValue: "1" },
    ],
  },
  {
    rank: 8,
    sailorName: "Josiah Zhi En Tan",
    sailNumber: "1978",
    gender: "M",
    schoolName: "Victoria School",
    club: "ONE\u00b015 Marina",
    nationality: "SGP",
    yearOfBirth: 2010,
    totalScore: 50,
    nettScore: 38,
    races: [
      { raceNumber: 1, score: 3, rawValue: "3" },
      { raceNumber: 2, score: 12, rawValue: "12", discarded: true },
      { raceNumber: 3, score: 12, rawValue: "12" },
      { raceNumber: 4, score: 7, rawValue: "7" },
      { raceNumber: 5, score: 9, rawValue: "9" },
      { raceNumber: 6, score: 7, rawValue: "7" },
    ],
  },
  {
    rank: 9,
    sailorName: "Yuei Jit Foo",
    sailNumber: "221686",
    gender: "M",
    schoolName: "Anderson Serangoon Junior College",
    club: "PAssion Wave",
    nationality: "SGP",
    yearOfBirth: 2009,
    totalScore: 50,
    nettScore: 38,
    races: [
      { raceNumber: 1, score: 11, rawValue: "11" },
      { raceNumber: 2, score: 6, rawValue: "6" },
      { raceNumber: 3, score: 6, rawValue: "6" },
      { raceNumber: 4, score: 4, rawValue: "4" },
      { raceNumber: 5, score: 12, rawValue: "12", discarded: true },
      { raceNumber: 6, score: 11, rawValue: "11" },
    ],
  },
  {
    rank: 10,
    sailorName: "Darren Lai",
    sailNumber: "222257",
    gender: "M",
    ageCategory: "15&U",
    schoolName: "St. Joseph's Institution",
    club: "Royal Varuna Yacht Club",
    nationality: "SGP",
    yearOfBirth: 2011,
    totalScore: 48,
    nettScore: 38,
    races: [
      { raceNumber: 1, score: 8, rawValue: "8" },
      { raceNumber: 2, score: 9, rawValue: "9" },
      { raceNumber: 3, score: 8, rawValue: "8" },
      { raceNumber: 4, score: 6, rawValue: "6" },
      { raceNumber: 5, score: 7, rawValue: "7" },
      { raceNumber: 6, score: 10, rawValue: "10", discarded: true },
    ],
  },
  {
    rank: 11,
    sailorName: "Zachary Khoo",
    sailNumber: "51",
    gender: "M",
    club: "PAssion Wave",
    nationality: "SGP",
    yearOfBirth: 2005,
    totalScore: 57,
    nettScore: 43,
    races: [
      { raceNumber: 1, score: 9, rawValue: "9" },
      { raceNumber: 2, score: 4, rawValue: "4" },
      { raceNumber: 3, score: 9, rawValue: "9" },
      { raceNumber: 4, score: 10, rawValue: "10" },
      { raceNumber: 5, score: 11, rawValue: "11" },
      { raceNumber: 6, score: 14, rawValue: "14", discarded: true },
    ],
  },
  {
    rank: 12,
    sailorName: "Jayden Teo",
    sailNumber: "214813",
    gender: "M",
    schoolName: "St. Joseph's Institution",
    club: "PAssion Wave",
    nationality: "SGP",
    yearOfBirth: 2009,
    totalScore: 64,
    nettScore: 50,
    races: [
      { raceNumber: 1, score: 12, rawValue: "12" },
      { raceNumber: 2, score: 10, rawValue: "10" },
      { raceNumber: 3, score: 14, rawValue: "14", discarded: true },
      { raceNumber: 4, score: 11, rawValue: "11" },
      { raceNumber: 5, score: 8, rawValue: "8" },
      { raceNumber: 6, score: 9, rawValue: "9" },
    ],
  },
  {
    rank: 13,
    sailorName: "Rohit Behl",
    sailNumber: "221931",
    gender: "M",
    club: "Changi Sailing Club",
    nationality: "SGP",
    yearOfBirth: 1974,
    totalScore: 70,
    nettScore: 55,
    races: [
      { raceNumber: 1, score: 10, rawValue: "10" },
      { raceNumber: 2, score: 13, rawValue: "13" },
      { raceNumber: 3, score: 11, rawValue: "11" },
      { raceNumber: 4, score: 8, rawValue: "8" },
      { raceNumber: 5, score: 15, rawValue: "15", discarded: true },
      { raceNumber: 6, score: 13, rawValue: "13" },
    ],
  },
  {
    rank: 14,
    sailorName: "Jonathan Jian Yi Ho",
    sailNumber: "214848",
    gender: "M",
    schoolName: "Anglo-Chinese School (Independent)",
    club: "PAssion Wave",
    nationality: "SGP",
    yearOfBirth: 2010,
    totalScore: 78,
    nettScore: 63,
    races: [
      { raceNumber: 1, score: 15, rawValue: "15", discarded: true },
      { raceNumber: 2, score: 14, rawValue: "14" },
      { raceNumber: 3, score: 15, rawValue: "15" },
      { raceNumber: 4, score: 13, rawValue: "13" },
      { raceNumber: 5, score: 13, rawValue: "13" },
      { raceNumber: 6, score: 8, rawValue: "8" },
    ],
  },
  {
    rank: 15,
    sailorName: "Cleo En Rui Seah",
    sailNumber: "224379",
    gender: "F",
    schoolName: "Ngee Ann Polytechnic",
    club: "SAF Yacht Club",
    nationality: "SGP",
    yearOfBirth: 2009,
    totalScore: 78,
    nettScore: 64,
    races: [
      { raceNumber: 1, score: 14, rawValue: "14", discarded: true },
      { raceNumber: 2, score: 11, rawValue: "11" },
      { raceNumber: 3, score: 13, rawValue: "13" },
      { raceNumber: 4, score: 14, rawValue: "14" },
      { raceNumber: 5, score: 14, rawValue: "14" },
      { raceNumber: 6, score: 12, rawValue: "12" },
    ],
  },
  {
    rank: 16,
    sailorName: "Aurick You Shun Leow",
    sailNumber: "67",
    gender: "M",
    schoolName: "Raffles Institution",
    club: "SAF Yacht Club",
    nationality: "SGP",
    yearOfBirth: 2008,
    totalScore: 102,
    nettScore: 85,
    isDns: true,
    races: [
      { raceNumber: 1, score: 17, rawValue: "17 DNC", scoringCode: "DNC", discarded: true },
      { raceNumber: 2, score: 17, rawValue: "17 DNC", scoringCode: "DNC" },
      { raceNumber: 3, score: 17, rawValue: "17 DNC", scoringCode: "DNC" },
      { raceNumber: 4, score: 17, rawValue: "17 DNC", scoringCode: "DNC" },
      { raceNumber: 5, score: 17, rawValue: "17 DNC", scoringCode: "DNC" },
      { raceNumber: 6, score: 17, rawValue: "17 DNC", scoringCode: "DNC" },
    ],
  },
];

export const SYSC_2026_ILCA6_RESULTS: Ilca6CompetitorResult[] = [
  {
    rank: 1,
    sailorName: "Austin Jia Yu Yeo",
    sailNumber: "221062",
    gender: "M",
    schoolName: "Anglo-Chinese School (Independent)",
    club: "SAF Yacht Club",
    nationality: "SGP",
    yearOfBirth: 2009,
    totalScore: 37,
    nettScore: 19,
    races: [
      { raceNumber: 1, score: 1, rawValue: "1" },
      { raceNumber: 2, score: 1, rawValue: "1" },
      { raceNumber: 3, score: 1, rawValue: "1" },
      { raceNumber: 4, score: 1, rawValue: "1" },
      { raceNumber: 5, score: 4, rawValue: "4" },
      { raceNumber: 6, score: 1, rawValue: "1" },
      { raceNumber: 7, score: 1, rawValue: "1" },
      { raceNumber: 8, score: 3, rawValue: "3" },
      { raceNumber: 9, score: 2, rawValue: "2" },
      { raceNumber: 10, score: 4, rawValue: "4" },
      { raceNumber: 11, score: 12, rawValue: "12", discarded: true },
      { raceNumber: 12, score: 6, rawValue: "6", discarded: true },
    ],
  },
  {
    rank: 2,
    sailorName: "Aurick You Shun Leow",
    sailNumber: "214737",
    gender: "M",
    schoolName: "Raffles Institution",
    club: "SAF Yacht Club",
    nationality: "SGP",
    yearOfBirth: 2008,
    totalScore: 45,
    nettScore: 22,
    races: [
      { raceNumber: 1, score: 2, rawValue: "2" },
      { raceNumber: 2, score: 17, rawValue: "DNF 17", scoringCode: "DNF", discarded: true },
      { raceNumber: 3, score: 2, rawValue: "2" },
      { raceNumber: 4, score: 6, rawValue: "6", discarded: true },
      { raceNumber: 5, score: 3, rawValue: "3" },
      { raceNumber: 6, score: 3, rawValue: "3" },
      { raceNumber: 7, score: 3, rawValue: "3" },
      { raceNumber: 8, score: 1, rawValue: "1" },
      { raceNumber: 9, score: 1, rawValue: "1" },
      { raceNumber: 10, score: 2, rawValue: "2" },
      { raceNumber: 11, score: 3, rawValue: "3" },
      { raceNumber: 12, score: 2, rawValue: "2" },
    ],
  },
  {
    rank: 3,
    sailorName: "Eitan Oh",
    sailNumber: "224717",
    gender: "M",
    schoolName: "Raffles Institution",
    club: "SAF Yacht Club",
    nationality: "SGP",
    yearOfBirth: 2008,
    totalScore: 39,
    nettScore: 26,
    races: [
      { raceNumber: 1, score: 3, rawValue: "3" },
      { raceNumber: 2, score: 3, rawValue: "3" },
      { raceNumber: 3, score: 4, rawValue: "4" },
      { raceNumber: 4, score: 2, rawValue: "2" },
      { raceNumber: 5, score: 2, rawValue: "2" },
      { raceNumber: 6, score: 2, rawValue: "2" },
      { raceNumber: 7, score: 8, rawValue: "8", discarded: true },
      { raceNumber: 8, score: 4, rawValue: "4" },
      { raceNumber: 9, score: 5, rawValue: "5", discarded: true },
      { raceNumber: 10, score: 3, rawValue: "3" },
      { raceNumber: 11, score: 2, rawValue: "2" },
      { raceNumber: 12, score: 1, rawValue: "1" },
    ],
  },
  {
    rank: 4,
    sailorName: "Gordon Alexander Allan",
    sailNumber: "221058",
    gender: "M",
    schoolName: "Anglo-Chinese School (Independent)",
    club: "Royal Varuna Yacht Club",
    nationality: "SGP",
    yearOfBirth: 2010,
    totalScore: 46,
    nettScore: 34,
    races: [
      { raceNumber: 1, score: 4, rawValue: "4" },
      { raceNumber: 2, score: 6, rawValue: "6", discarded: true },
      { raceNumber: 3, score: 3, rawValue: "3" },
      { raceNumber: 4, score: 3, rawValue: "3" },
      { raceNumber: 5, score: 5, rawValue: "5" },
      { raceNumber: 6, score: 4, rawValue: "4" },
      { raceNumber: 7, score: 5, rawValue: "5" },
      { raceNumber: 8, score: 2, rawValue: "2" },
      { raceNumber: 9, score: 3, rawValue: "3" },
      { raceNumber: 10, score: 1, rawValue: "1" },
      { raceNumber: 11, score: 6, rawValue: "6", discarded: true },
      { raceNumber: 12, score: 4, rawValue: "4" },
    ],
  },
  {
    rank: 5,
    sailorName: "Sarah Rui-En Yong",
    sailNumber: "18",
    gender: "F",
    schoolName: "Nanyang Polytechnic",
    club: "Royal Varuna Yacht Club",
    nationality: "SGP",
    yearOfBirth: 2008,
    totalScore: 67,
    nettScore: 47,
    races: [
      { raceNumber: 1, score: 5, rawValue: "5" },
      { raceNumber: 2, score: 4, rawValue: "4" },
      { raceNumber: 3, score: 7, rawValue: "7" },
      { raceNumber: 4, score: 11, rawValue: "11", discarded: true },
      { raceNumber: 5, score: 1, rawValue: "1" },
      { raceNumber: 6, score: 9, rawValue: "9", discarded: true },
      { raceNumber: 7, score: 2, rawValue: "2" },
      { raceNumber: 8, score: 7, rawValue: "7" },
      { raceNumber: 9, score: 4, rawValue: "4" },
      { raceNumber: 10, score: 7, rawValue: "7" },
      { raceNumber: 11, score: 5, rawValue: "5" },
      { raceNumber: 12, score: 5, rawValue: "5" },
    ],
  },
  {
    rank: 6,
    sailorName: "Keira Carlyle",
    sailNumber: "25",
    gender: "F",
    club: "SAF Yacht Club",
    nationality: "SGP",
    yearOfBirth: 2006,
    totalScore: 65,
    nettScore: 49,
    races: [
      { raceNumber: 1, score: 8, rawValue: "8", discarded: true },
      { raceNumber: 2, score: 2, rawValue: "2" },
      { raceNumber: 3, score: 8, rawValue: "8", discarded: true },
      { raceNumber: 4, score: 7, rawValue: "7" },
      { raceNumber: 5, score: 6, rawValue: "6" },
      { raceNumber: 6, score: 6, rawValue: "6" },
      { raceNumber: 7, score: 4, rawValue: "4" },
      { raceNumber: 8, score: 5, rawValue: "5" },
      { raceNumber: 9, score: 6, rawValue: "6" },
      { raceNumber: 10, score: 6, rawValue: "6" },
      { raceNumber: 11, score: 4, rawValue: "4" },
      { raceNumber: 12, score: 3, rawValue: "3" },
    ],
  },
  {
    rank: 7,
    sailorName: "Zixi Lu",
    sailNumber: "214664",
    gender: "M",
    club: "Changi Sailing Club",
    nationality: "CHN",
    yearOfBirth: 2009,
    totalScore: 110,
    nettScore: 80,
    races: [
      { raceNumber: 1, score: 6, rawValue: "6" },
      { raceNumber: 2, score: 8, rawValue: "8" },
      { raceNumber: 3, score: 5, rawValue: "5" },
      { raceNumber: 4, score: 5, rawValue: "5" },
      { raceNumber: 5, score: 13, rawValue: "13", discarded: true },
      { raceNumber: 6, score: 8, rawValue: "8" },
      { raceNumber: 7, score: 9, rawValue: "9" },
      { raceNumber: 8, score: 11, rawValue: "11" },
      { raceNumber: 9, score: 12, rawValue: "12" },
      { raceNumber: 10, score: 17, rawValue: "DNC 17", scoringCode: "DNC", discarded: true },
      { raceNumber: 11, score: 8, rawValue: "8" },
      { raceNumber: 12, score: 8, rawValue: "8" },
    ],
  },
  {
    rank: 8,
    sailorName: "Asher-James Nair",
    sailNumber: "185201",
    gender: "M",
    schoolName: "St. Joseph's Institution",
    club: "PAssion Wave",
    nationality: "SGP",
    yearOfBirth: 2008,
    totalScore: 117,
    nettScore: 87,
    races: [
      { raceNumber: 1, score: 14, rawValue: "14" },
      { raceNumber: 2, score: 12, rawValue: "12" },
      { raceNumber: 3, score: 15, rawValue: "15", discarded: true },
      { raceNumber: 4, score: 15, rawValue: "15", discarded: true },
      { raceNumber: 5, score: 8, rawValue: "8" },
      { raceNumber: 6, score: 7, rawValue: "7" },
      { raceNumber: 7, score: 10, rawValue: "10" },
      { raceNumber: 8, score: 8, rawValue: "8" },
      { raceNumber: 9, score: 9, rawValue: "9" },
      { raceNumber: 10, score: 5, rawValue: "5" },
      { raceNumber: 11, score: 7, rawValue: "7" },
      { raceNumber: 12, score: 7, rawValue: "7" },
    ],
  },
  {
    rank: 9,
    sailorName: "Darren Lai",
    sailNumber: "222257",
    gender: "M",
    ageCategory: "15&U",
    schoolName: "St. Joseph's Institution",
    club: "Royal Varuna Yacht Club",
    nationality: "SGP",
    yearOfBirth: 2011,
    totalScore: 119,
    nettScore: 91,
    races: [
      { raceNumber: 1, score: 10, rawValue: "10" },
      { raceNumber: 2, score: 11, rawValue: "11" },
      { raceNumber: 3, score: 6, rawValue: "6" },
      { raceNumber: 4, score: 4, rawValue: "4" },
      { raceNumber: 5, score: 7, rawValue: "7" },
      { raceNumber: 6, score: 11, rawValue: "11" },
      { raceNumber: 7, score: 14, rawValue: "14", discarded: true },
      { raceNumber: 8, score: 14, rawValue: "14", discarded: true },
      { raceNumber: 9, score: 10, rawValue: "10" },
      { raceNumber: 10, score: 9, rawValue: "9" },
      { raceNumber: 11, score: 13, rawValue: "13" },
      { raceNumber: 12, score: 10, rawValue: "10" },
    ],
  },
  {
    rank: 10,
    sailorName: "Jonathan Jian Yi Ho",
    sailNumber: "214848",
    gender: "M",
    schoolName: "Anglo-Chinese School (Independent)",
    club: "PAssion Wave",
    nationality: "SGP",
    yearOfBirth: 2010,
    totalScore: 118,
    nettScore: 94,
    races: [
      { raceNumber: 1, score: 11, rawValue: "11" },
      { raceNumber: 2, score: 7, rawValue: "7" },
      { raceNumber: 3, score: 12, rawValue: "12", discarded: true },
      { raceNumber: 4, score: 9, rawValue: "9" },
      { raceNumber: 5, score: 12, rawValue: "12", discarded: true },
      { raceNumber: 6, score: 12, rawValue: "12" },
      { raceNumber: 7, score: 11, rawValue: "11" },
      { raceNumber: 8, score: 6, rawValue: "6" },
      { raceNumber: 9, score: 8, rawValue: "8" },
      { raceNumber: 10, score: 11, rawValue: "11" },
      { raceNumber: 11, score: 10, rawValue: "10" },
      { raceNumber: 12, score: 9, rawValue: "9" },
    ],
  },
  {
    rank: 11,
    sailorName: "Jayden Teo",
    sailNumber: "214813",
    gender: "M",
    schoolName: "St. Joseph's Institution",
    club: "PAssion Wave",
    nationality: "SGP",
    yearOfBirth: 2009,
    totalScore: 125,
    nettScore: 98,
    races: [
      { raceNumber: 1, score: 13, rawValue: "13", discarded: true },
      { raceNumber: 2, score: 13, rawValue: "13" },
      { raceNumber: 3, score: 10, rawValue: "10" },
      { raceNumber: 4, score: 10, rawValue: "10" },
      { raceNumber: 5, score: 9, rawValue: "9" },
      { raceNumber: 6, score: 14, rawValue: "14", discarded: true },
      { raceNumber: 7, score: 7, rawValue: "7" },
      { raceNumber: 8, score: 12, rawValue: "12" },
      { raceNumber: 9, score: 7, rawValue: "7" },
      { raceNumber: 10, score: 8, rawValue: "8" },
      { raceNumber: 11, score: 11, rawValue: "11" },
      { raceNumber: 12, score: 11, rawValue: "11" },
    ],
  },
  {
    rank: 12,
    sailorName: "Cleo En Rui Seah",
    sailNumber: "224379",
    gender: "F",
    schoolName: "Ngee Ann Polytechnic",
    club: "SAF Yacht Club",
    nationality: "SGP",
    yearOfBirth: 2009,
    totalScore: 131,
    nettScore: 100,
    races: [
      { raceNumber: 1, score: 16, rawValue: "16", discarded: true },
      { raceNumber: 2, score: 10, rawValue: "10" },
      { raceNumber: 3, score: 14, rawValue: "14" },
      { raceNumber: 4, score: 13, rawValue: "13" },
      { raceNumber: 5, score: 11, rawValue: "11" },
      { raceNumber: 6, score: 5, rawValue: "5" },
      { raceNumber: 7, score: 12, rawValue: "12" },
      { raceNumber: 8, score: 9, rawValue: "9" },
      { raceNumber: 9, score: 15, rawValue: "15", discarded: true },
      { raceNumber: 10, score: 13, rawValue: "13" },
      { raceNumber: 11, score: 1, rawValue: "1" },
      { raceNumber: 12, score: 12, rawValue: "12" },
    ],
  },
  {
    rank: 13,
    sailorName: "Josiah Zhi En Tan",
    sailNumber: "1978",
    gender: "M",
    schoolName: "Victoria School",
    club: "ONE\u00b015 Marina",
    nationality: "SGP",
    yearOfBirth: 2010,
    totalScore: 133,
    nettScore: 105,
    races: [
      { raceNumber: 1, score: 12, rawValue: "12" },
      { raceNumber: 2, score: 5, rawValue: "5" },
      { raceNumber: 3, score: 13, rawValue: "13" },
      { raceNumber: 4, score: 12, rawValue: "12" },
      { raceNumber: 5, score: 14, rawValue: "14", discarded: true },
      { raceNumber: 6, score: 10, rawValue: "10" },
      { raceNumber: 7, score: 6, rawValue: "6" },
      { raceNumber: 8, score: 13, rawValue: "13" },
      { raceNumber: 9, score: 11, rawValue: "11" },
      { raceNumber: 10, score: 10, rawValue: "10" },
      { raceNumber: 11, score: 14, rawValue: "14", discarded: true },
      { raceNumber: 12, score: 13, rawValue: "13" },
    ],
  },
  {
    rank: 14,
    sailorName: "Elizabeth Victoria Say",
    sailNumber: "214873",
    gender: "F",
    schoolName: "Dunman High School",
    club: "Royal Varuna Yacht Club",
    nationality: "SGP",
    yearOfBirth: 2010,
    totalScore: 146,
    nettScore: 115,
    races: [
      { raceNumber: 1, score: 9, rawValue: "9" },
      { raceNumber: 2, score: 15, rawValue: "15", discarded: true },
      { raceNumber: 3, score: 11, rawValue: "11" },
      { raceNumber: 4, score: 16, rawValue: "16", discarded: true },
      { raceNumber: 5, score: 10, rawValue: "10" },
      { raceNumber: 6, score: 13, rawValue: "13" },
      { raceNumber: 7, score: 13, rawValue: "13" },
      { raceNumber: 8, score: 10, rawValue: "10" },
      { raceNumber: 9, score: 14, rawValue: "14" },
      { raceNumber: 10, score: 12, rawValue: "12" },
      { raceNumber: 11, score: 9, rawValue: "9" },
      { raceNumber: 12, score: 14, rawValue: "14" },
    ],
  },
  {
    rank: 15,
    sailorName: "Yuei Jit Foo",
    sailNumber: "221686",
    gender: "M",
    schoolName: "Anderson Serangoon Junior College",
    club: "PAssion Wave",
    nationality: "SGP",
    yearOfBirth: 2009,
    totalScore: 169,
    nettScore: 135,
    races: [
      { raceNumber: 1, score: 7, rawValue: "7" },
      { raceNumber: 2, score: 9, rawValue: "9" },
      { raceNumber: 3, score: 9, rawValue: "9" },
      { raceNumber: 4, score: 8, rawValue: "8" },
      { raceNumber: 5, score: 17, rawValue: "DNC 17", scoringCode: "DNC", discarded: true },
      { raceNumber: 6, score: 17, rawValue: "DNC 17", scoringCode: "DNC", discarded: true },
      { raceNumber: 7, score: 17, rawValue: "DNC 17", scoringCode: "DNC" },
      { raceNumber: 8, score: 17, rawValue: "DNC 17", scoringCode: "DNC" },
      { raceNumber: 9, score: 17, rawValue: "DNC 17", scoringCode: "DNC" },
      { raceNumber: 10, score: 17, rawValue: "DNC 17", scoringCode: "DNC" },
      { raceNumber: 11, score: 17, rawValue: "DNC 17", scoringCode: "DNC" },
      { raceNumber: 12, score: 17, rawValue: "DNC 17", scoringCode: "DNC" },
    ],
  },
  {
    rank: 16,
    sailorName: "Arabelle En Xi Tan",
    sailNumber: "221690",
    gender: "F",
    schoolName: "Tanjong Katong Girls' School",
    club: "PAssion Wave",
    nationality: "SGP",
    yearOfBirth: 2010,
    totalScore: 177,
    nettScore: 145,
    races: [
      { raceNumber: 1, score: 15, rawValue: "15" },
      { raceNumber: 2, score: 14, rawValue: "14" },
      { raceNumber: 3, score: 16, rawValue: "16", discarded: true },
      { raceNumber: 4, score: 14, rawValue: "14" },
      { raceNumber: 5, score: 15, rawValue: "15" },
      { raceNumber: 6, score: 16, rawValue: "DNF 16", scoringCode: "DNF", discarded: true },
      { raceNumber: 7, score: 15, rawValue: "15" },
      { raceNumber: 8, score: 15, rawValue: "15" },
      { raceNumber: 9, score: 13, rawValue: "13" },
      { raceNumber: 10, score: 14, rawValue: "14" },
      { raceNumber: 11, score: 15, rawValue: "15" },
      { raceNumber: 12, score: 15, rawValue: "15" },
    ],
  },
];

export const TEMASEK_2026_ILCA6_RESULTS: Ilca6CompetitorResult[] = [
  {
    rank: 1,
    sailorName: "Keira Marie Carlyle",
    sailNumber: "225225",
    gender: "F",
    club: "SAF Yacht Club",
    nationality: "SGP",
    totalScore: 8,
    nettScore: 5,
    races: [
      { raceNumber: 1, score: 1, rawValue: "1" },
      { raceNumber: 2, score: 1, rawValue: "1" },
      { raceNumber: 3, score: 2, rawValue: "2" },
      { raceNumber: 4, score: 1, rawValue: "1" },
      { raceNumber: 5, score: 3, rawValue: "3", discarded: true },
    ],
  },
  {
    rank: 2,
    sailorName: "Kenan Kee Zen Tan",
    sailNumber: "1",
    gender: "M",
    club: "Royal Varuna Yacht Club",
    nationality: "SGP",
    totalScore: 13,
    nettScore: 8,
    races: [
      { raceNumber: 1, score: 2, rawValue: "2" },
      { raceNumber: 2, score: 2, rawValue: "2" },
      { raceNumber: 3, score: 5, rawValue: "5", discarded: true },
      { raceNumber: 4, score: 3, rawValue: "3" },
      { raceNumber: 5, score: 1, rawValue: "1" },
    ],
  },
  {
    rank: 3,
    sailorName: "Nia Zahedi",
    sailNumber: "224245",
    gender: "F",
    novice: true,
    schoolName: "Raffles Institution",
    club: "PAssion Wave",
    nationality: "SGP",
    totalScore: 16,
    nettScore: 11,
    races: [
      { raceNumber: 1, score: 3, rawValue: "3" },
      { raceNumber: 2, score: 5, rawValue: "5", discarded: true },
      { raceNumber: 3, score: 4, rawValue: "4" },
      { raceNumber: 4, score: 2, rawValue: "2" },
      { raceNumber: 5, score: 2, rawValue: "2" },
    ],
  },
  {
    rank: 4,
    sailorName: "Sarah Rui-En Yong",
    sailNumber: "221689",
    gender: "F",
    schoolName: "Nanyang Polytechnic",
    club: "Royal Varuna Yacht Club",
    nationality: "SGP",
    totalScore: 24,
    nettScore: 14,
    races: [
      { raceNumber: 1, score: 6, rawValue: "6" },
      { raceNumber: 2, score: 3, rawValue: "3" },
      { raceNumber: 3, score: 1, rawValue: "1" },
      { raceNumber: 4, score: 4, rawValue: "4" },
      { raceNumber: 5, score: 10, rawValue: "10", discarded: true },
    ],
  },
  {
    rank: 5,
    sailorName: "Gabi Oh",
    sailNumber: "224717",
    gender: "F",
    novice: true,
    schoolName: "Raffles Institution",
    club: "SAF Yacht Club",
    nationality: "SGP",
    totalScore: 26,
    nettScore: 18,
    races: [
      { raceNumber: 1, score: 4, rawValue: "4" },
      { raceNumber: 2, score: 7, rawValue: "7" },
      { raceNumber: 3, score: 3, rawValue: "3" },
      { raceNumber: 4, score: 8, rawValue: "8", discarded: true },
      { raceNumber: 5, score: 4, rawValue: "4" },
    ],
  },
  {
    rank: 6,
    sailorName: "Austin Jia Yu Yeo",
    sailNumber: "221062",
    gender: "M",
    schoolName: "Anglo-Chinese School (Independent)",
    club: "SAF Yacht Club",
    nationality: "SGP",
    totalScore: 27,
    nettScore: 20,
    races: [
      { raceNumber: 1, score: 5, rawValue: "5" },
      { raceNumber: 2, score: 4, rawValue: "4" },
      { raceNumber: 3, score: 6, rawValue: "6" },
      { raceNumber: 4, score: 5, rawValue: "5" },
      { raceNumber: 5, score: 7, rawValue: "7", discarded: true },
    ],
  },
  {
    rank: 7,
    sailorName: "Gordon Alexander Allan",
    sailNumber: "221058",
    gender: "M",
    schoolName: "Anglo-Chinese School (Independent)",
    club: "Royal Varuna Yacht Club",
    nationality: "SGP",
    totalScore: 36,
    nettScore: 27,
    races: [
      { raceNumber: 1, score: 8, rawValue: "8" },
      { raceNumber: 2, score: 6, rawValue: "6" },
      { raceNumber: 3, score: 7, rawValue: "7" },
      { raceNumber: 4, score: 6, rawValue: "6" },
      { raceNumber: 5, score: 9, rawValue: "9", discarded: true },
    ],
  },
  {
    rank: 8,
    sailorName: "Cleo En Rui Seah",
    sailNumber: "224379",
    gender: "F",
    schoolName: "Ngee Ann Polytechnic",
    club: "SAF Yacht Club",
    nationality: "SGP",
    totalScore: 41,
    nettScore: 31,
    races: [
      { raceNumber: 1, score: 9, rawValue: "9" },
      { raceNumber: 2, score: 8, rawValue: "8" },
      { raceNumber: 3, score: 8, rawValue: "8" },
      { raceNumber: 4, score: 10, rawValue: "10", discarded: true },
      { raceNumber: 5, score: 6, rawValue: "6" },
    ],
  },
  {
    rank: 9,
    sailorName: "Jayden Teo",
    sailNumber: "228158",
    gender: "M",
    schoolName: "St. Joseph's Institution",
    club: "PAssion Wave",
    nationality: "SGP",
    totalScore: 43,
    nettScore: 31,
    races: [
      { raceNumber: 1, score: 7, rawValue: "7" },
      { raceNumber: 2, score: 9, rawValue: "9" },
      { raceNumber: 3, score: 12, rawValue: "12 DSQ", scoringCode: "DSQ", discarded: true },
      { raceNumber: 4, score: 7, rawValue: "7" },
      { raceNumber: 5, score: 8, rawValue: "8" },
    ],
  },
  {
    rank: 10,
    sailorName: "Darren Lai",
    sailNumber: "222257",
    gender: "M",
    ageCategory: "15&U",
    schoolName: "St. Joseph's Institution",
    club: "Royal Varuna Yacht Club",
    nationality: "SGP",
    totalScore: 48,
    nettScore: 36,
    races: [
      { raceNumber: 1, score: 10, rawValue: "10" },
      { raceNumber: 2, score: 12, rawValue: "12 DSQ", scoringCode: "DSQ", discarded: true },
      { raceNumber: 3, score: 10, rawValue: "10" },
      { raceNumber: 4, score: 11, rawValue: "11" },
      { raceNumber: 5, score: 5, rawValue: "5" },
    ],
  },
  {
    rank: 11,
    sailorName: "Elizabeth Victoria Say",
    sailNumber: "214873",
    gender: "F",
    schoolName: "Dunman High School",
    club: "PAssion Wave",
    nationality: "SGP",
    totalScore: 50,
    nettScore: 39,
    races: [
      { raceNumber: 1, score: 11, rawValue: "11", discarded: true },
      { raceNumber: 2, score: 10, rawValue: "10" },
      { raceNumber: 3, score: 9, rawValue: "9" },
      { raceNumber: 4, score: 9, rawValue: "9" },
      { raceNumber: 5, score: 11, rawValue: "11" },
    ],
  },
];


export const SAFYC_2026_ILCA6_RESULTS: Ilca6CompetitorResult[] = [
  {
    rank: 1,
    sailorName: "Gordon Alexander Allan",
    sailNumber: "221058",
    gender: "M",
    club: "Others",
    nationality: "SGP",
    totalScore: 29.0,
    nettScore: 12.0,
    races: [
      { raceNumber: 1, score: 1.0, rawValue: "1.0" },
      { raceNumber: 2, score: 1.0, rawValue: "1.0" },
      { raceNumber: 3, score: 3.0, rawValue: "3.0" },
      { raceNumber: 4, score: 1.0, rawValue: "1.0" },
      { raceNumber: 5, score: 17.0, rawValue: "17.0 DNC", scoringCode: "DNC", discarded: true },
      { raceNumber: 6, score: 3.0, rawValue: "3.0" },
      { raceNumber: 7, score: 3.0, rawValue: "3.0" },
    ]
  },
  {
    rank: 2,
    sailorName: "Leow You Shun Aurick",
    sailNumber: "67",
    gender: "M",
    club: "SAF Yacht Club",
    nationality: "SGP",
    totalScore: 29.0,
    nettScore: 12.0,
    races: [
      { raceNumber: 1, score: 2.0, rawValue: "2.0" },
      { raceNumber: 2, score: 2.0, rawValue: "2.0" },
      { raceNumber: 3, score: 2.0, rawValue: "2.0" },
      { raceNumber: 4, score: 4.0, rawValue: "4.0" },
      { raceNumber: 5, score: 1.0, rawValue: "1.0" },
      { raceNumber: 6, score: 1.0, rawValue: "1.0" },
      { raceNumber: 7, score: 17.0, rawValue: "17.0 RET", scoringCode: "RET", discarded: true },
    ]
  },
  {
    rank: 3,
    sailorName: "Eitan Oh",
    sailNumber: "224717",
    gender: "M",
    club: "SAF Yacht Club",
    nationality: "SGP",
    totalScore: 21.0,
    nettScore: 14.0,
    races: [
      { raceNumber: 1, score: 5.0, rawValue: "5.0" },
      { raceNumber: 2, score: 7.0, rawValue: "7.0", discarded: true },
      { raceNumber: 3, score: 1.0, rawValue: "1.0" },
      { raceNumber: 4, score: 2.0, rawValue: "2.0" },
      { raceNumber: 5, score: 3.0, rawValue: "3.0" },
      { raceNumber: 6, score: 2.0, rawValue: "2.0" },
      { raceNumber: 7, score: 1.0, rawValue: "1.0" },
    ]
  },
  {
    rank: 4,
    sailorName: "Austin Yeo",
    sailNumber: "222727",
    gender: "M",
    club: "SAF Yacht Club",
    nationality: "SGP",
    totalScore: 29.0,
    nettScore: 21.0,
    races: [
      { raceNumber: 1, score: 4.0, rawValue: "4.0" },
      { raceNumber: 2, score: 3.0, rawValue: "3.0" },
      { raceNumber: 3, score: 8.0, rawValue: "8.0", discarded: true },
      { raceNumber: 4, score: 3.0, rawValue: "3.0" },
      { raceNumber: 5, score: 2.0, rawValue: "2.0" },
      { raceNumber: 6, score: 5.0, rawValue: "5.0" },
      { raceNumber: 7, score: 4.0, rawValue: "4.0" },
    ]
  },
  {
    rank: 5,
    sailorName: "Keira Marie Carlyle",
    sailNumber: "225225",
    gender: "F",
    club: "SAF Yacht Club",
    nationality: "SGP",
    totalScore: 33.0,
    nettScore: 26.0,
    races: [
      { raceNumber: 1, score: 3.0, rawValue: "3.0" },
      { raceNumber: 2, score: 5.0, rawValue: "5.0" },
      { raceNumber: 3, score: 7.0, rawValue: "7.0", discarded: true },
      { raceNumber: 4, score: 6.0, rawValue: "6.0" },
      { raceNumber: 5, score: 4.0, rawValue: "4.0" },
      { raceNumber: 6, score: 6.0, rawValue: "6.0" },
      { raceNumber: 7, score: 2.0, rawValue: "2.0" },
    ]
  },
  {
    rank: 6,
    sailorName: "Sarah Yong",
    sailNumber: "18",
    gender: "F",
    club: "Others",
    nationality: "SGP",
    totalScore: 54.0,
    nettScore: 41.0,
    races: [
      { raceNumber: 1, score: 9.0, rawValue: "9.0" },
      { raceNumber: 2, score: 4.0, rawValue: "4.0" },
      { raceNumber: 3, score: 6.0, rawValue: "6.0" },
      { raceNumber: 4, score: 13.0, rawValue: "13.0", discarded: true },
      { raceNumber: 5, score: 6.0, rawValue: "6.0" },
      { raceNumber: 6, score: 11.0, rawValue: "11.0" },
      { raceNumber: 7, score: 5.0, rawValue: "5.0" },
    ]
  },
  {
    rank: 7,
    sailorName: "Jayden Teo",
    sailNumber: "214813",
    gender: "M",
    club: "Others",
    nationality: "SGP",
    totalScore: 58.0,
    nettScore: 46.0,
    races: [
      { raceNumber: 1, score: 12.0, rawValue: "12.0", discarded: true },
      { raceNumber: 2, score: 8.0, rawValue: "8.0" },
      { raceNumber: 3, score: 4.0, rawValue: "4.0" },
      { raceNumber: 4, score: 10.0, rawValue: "10.0" },
      { raceNumber: 5, score: 7.0, rawValue: "7.0" },
      { raceNumber: 6, score: 8.0, rawValue: "8.0" },
      { raceNumber: 7, score: 9.0, rawValue: "9.0" },
    ]
  },
  {
    rank: 8,
    sailorName: "Asher-James Nair",
    sailNumber: "185201",
    gender: "M",
    club: "Others",
    nationality: "SGP",
    totalScore: 63.0,
    nettScore: 46.0,
    races: [
      { raceNumber: 1, score: 7.0, rawValue: "7.0" },
      { raceNumber: 2, score: 12.0, rawValue: "12.0" },
      { raceNumber: 3, score: 5.0, rawValue: "5.0" },
      { raceNumber: 4, score: 11.0, rawValue: "11.0" },
      { raceNumber: 5, score: 5.0, rawValue: "5.0" },
      { raceNumber: 6, score: 17.0, rawValue: "17.0 RET", scoringCode: "RET", discarded: true },
      { raceNumber: 7, score: 6.0, rawValue: "6.0" },
    ]
  },
  {
    rank: 9,
    sailorName: "Foo Yuei Jit",
    sailNumber: "221686",
    gender: "M",
    club: "Others",
    nationality: "SGP",
    totalScore: 62.0,
    nettScore: 49.0,
    races: [
      { raceNumber: 1, score: 10.0, rawValue: "10.0" },
      { raceNumber: 2, score: 13.0, rawValue: "13.0", discarded: true },
      { raceNumber: 3, score: 9.0, rawValue: "9.0" },
      { raceNumber: 4, score: 5.0, rawValue: "5.0" },
      { raceNumber: 5, score: 11.0, rawValue: "11.0" },
      { raceNumber: 6, score: 7.0, rawValue: "7.0" },
      { raceNumber: 7, score: 7.0, rawValue: "7.0" },
    ]
  },
  {
    rank: 10,
    sailorName: "Darren Lai",
    sailNumber: "222257",
    gender: "M",
    club: "Others",
    nationality: "SGP",
    totalScore: 70.0,
    nettScore: 55.0,
    races: [
      { raceNumber: 1, score: 13.0, rawValue: "13.0" },
      { raceNumber: 2, score: 6.0, rawValue: "6.0" },
      { raceNumber: 3, score: 15.0, rawValue: "15.0", discarded: true },
      { raceNumber: 4, score: 9.0, rawValue: "9.0" },
      { raceNumber: 5, score: 12.0, rawValue: "12.0" },
      { raceNumber: 6, score: 4.0, rawValue: "4.0" },
      { raceNumber: 7, score: 11.0, rawValue: "11.0" },
    ]
  },
  {
    rank: 11,
    sailorName: "Josiah Tan Zhi En",
    sailNumber: "1978",
    gender: "M",
    club: "Others",
    nationality: "SGP",
    totalScore: 73.0,
    nettScore: 57.0,
    races: [
      { raceNumber: 1, score: 11.0, rawValue: "11.0" },
      { raceNumber: 2, score: 16.0, rawValue: "16.0", discarded: true },
      { raceNumber: 3, score: 11.0, rawValue: "11.0" },
      { raceNumber: 4, score: 8.0, rawValue: "8.0" },
      { raceNumber: 5, score: 10.0, rawValue: "10.0" },
      { raceNumber: 6, score: 9.0, rawValue: "9.0" },
      { raceNumber: 7, score: 8.0, rawValue: "8.0" },
    ]
  },
  {
    rank: 12,
    sailorName: "Elizabeth Victoria Say",
    sailNumber: "214873",
    gender: "F",
    club: "Others",
    nationality: "SGP",
    totalScore: 74.0,
    nettScore: 59.0,
    races: [
      { raceNumber: 1, score: 8.0, rawValue: "8.0" },
      { raceNumber: 2, score: 15.0, rawValue: "15.0", discarded: true },
      { raceNumber: 3, score: 13.0, rawValue: "13.0" },
      { raceNumber: 4, score: 7.0, rawValue: "7.0" },
      { raceNumber: 5, score: 8.0, rawValue: "8.0" },
      { raceNumber: 6, score: 10.0, rawValue: "10.0" },
      { raceNumber: 7, score: 13.0, rawValue: "13.0" },
    ]
  },
  {
    rank: 13,
    sailorName: "Seah En Rui Cleo",
    sailNumber: "224379",
    gender: "F",
    club: "SAF Yacht Club",
    nationality: "SGP",
    totalScore: 85.0,
    nettScore: 70.0,
    races: [
      { raceNumber: 1, score: 14.0, rawValue: "14.0" },
      { raceNumber: 2, score: 9.0, rawValue: "9.0" },
      { raceNumber: 3, score: 12.0, rawValue: "12.0" },
      { raceNumber: 4, score: 15.0, rawValue: "15.0", discarded: true },
      { raceNumber: 5, score: 13.0, rawValue: "13.0" },
      { raceNumber: 6, score: 12.0, rawValue: "12.0" },
      { raceNumber: 7, score: 10.0, rawValue: "10.0" },
    ]
  },
  {
    rank: 14,
    sailorName: "Ho Jian Yi Jonathan",
    sailNumber: "214848",
    gender: "M",
    club: "Others",
    nationality: "SGP",
    totalScore: 86.0,
    nettScore: 71.0,
    races: [
      { raceNumber: 1, score: 15.0, rawValue: "15.0", discarded: true },
      { raceNumber: 2, score: 11.0, rawValue: "11.0" },
      { raceNumber: 3, score: 14.0, rawValue: "14.0" },
      { raceNumber: 4, score: 12.0, rawValue: "12.0" },
      { raceNumber: 5, score: 9.0, rawValue: "9.0" },
      { raceNumber: 6, score: 13.0, rawValue: "13.0" },
      { raceNumber: 7, score: 12.0, rawValue: "12.0" },
    ]
  },
  {
    rank: 15,
    sailorName: "Tristan Joseph Low",
    sailNumber: "33",
    gender: "M",
    club: "SAF Yacht Club",
    nationality: "SGP",
    totalScore: 91.0,
    nettScore: 74.0,
    races: [
      { raceNumber: 1, score: 6.0, rawValue: "6.0" },
      { raceNumber: 2, score: 10.0, rawValue: "10.0" },
      { raceNumber: 3, score: 10.0, rawValue: "10.0" },
      { raceNumber: 4, score: 14.0, rawValue: "14.0" },
      { raceNumber: 5, score: 17.0, rawValue: "17.0 DNC", scoringCode: "DNC", discarded: true },
      { raceNumber: 6, score: 17.0, rawValue: "17.0 DNC", scoringCode: "DNC" },
      { raceNumber: 7, score: 17.0, rawValue: "17.0 DNC", scoringCode: "DNC" },
    ]
  },
  {
    rank: 16,
    sailorName: "Angela Sabbatino",
    sailNumber: "209145",
    gender: "F",
    club: "Others",
    nationality: "SGP",
    totalScore: 107.0,
    nettScore: 90.0,
    races: [
      { raceNumber: 1, score: 16.0, rawValue: "16.0" },
      { raceNumber: 2, score: 14.0, rawValue: "14.0" },
      { raceNumber: 3, score: 16.0, rawValue: "16.0" },
      { raceNumber: 4, score: 16.0, rawValue: "16.0" },
      { raceNumber: 5, score: 14.0, rawValue: "14.0" },
      { raceNumber: 6, score: 17.0, rawValue: "17.0 RET", scoringCode: "RET", discarded: true },
      { raceNumber: 7, score: 14.0, rawValue: "14.0" },
    ]
  },
];

export const ILCA6_STATIC_REGATTAS: RegattaRecord[] = [
  {
    id: "safyc-2026-ilca-6",
    name: "22nd SAFYC Regatta 2026 (ILCA 6)",
    slug: "safyc-2026-ilca-6",
    date: "2026-02-14",
    endDate: "2026-02-15",
    boatClass: "ILCA 6",
    division: "Open",
    totalFleetSize: 16,
    raceCount: 7,
    geography: "SG",
    countsForRanking: true,
    venue: "NSRCC Seasports Centre, Singapore",
    organizer: "SAF Yacht Club",
    norUrl: "https://www.racingrulesofsailing.org/documents/13551/event",
    registrationUrl: "https://www.safyc.org.sg",
    scheduleNotes: "22nd SAFYC Regatta 2026 ILCA 6 fleet: 16 entries, 7 races sailed (1 discard).",
  },

  {
    id: "reg-pulau-ujong-2026-ilca-6",
    name: "Pulau Ujong Regatta 2026 (ILCA 6)",
    slug: "pulau-ujong-2026-ilca-6",
    date: "2026-02-21",
    endDate: "2026-02-22",
    boatClass: "ILCA 6",
    division: "Open",
    totalFleetSize: 16,
    raceCount: 6,
    geography: "SG",
    countsForRanking: true,
    venue: "National Sailing Centre, Singapore",
    organizer: "Singapore Sailing Federation",
    norUrl: "https://www.racingrulesofsailing.org/documents/13180/event",
    scheduleNotes: "Pulau Ujong Regatta 2026 ILCA 6 fleet: 16 entries, 6 races sailed (1 discard).",
  },
  {
    id: "reg-sysc-2026-ilca-6",
    name: "Singapore Youth Sailing Championships 2026 (ILCA 6)",
    slug: "sysc-2026-ilca-6",
    date: "2026-03-14",
    endDate: "2026-03-17",
    boatClass: "ILCA 6",
    division: "Open",
    totalFleetSize: 16,
    raceCount: 12,
    geography: "SG",
    countsForRanking: true,
    venue: "National Sailing Centre, Singapore",
    organizer: "Singapore Sailing Federation",
    norUrl: "https://www.racingrulesofsailing.org/documents/13601/event",
    scheduleNotes: "Singapore Youth Sailing Championships 2026 ILCA 6 fleet: 16 entries, 12 races sailed (2 discards).",
  },
  {
    id: "reg-temasek-2026-ilca-6",
    name: "Temasek Regatta 2026 (ILCA 6)",
    slug: "temasek-2026-ilca-6",
    date: "2026-06-20",
    endDate: "2026-06-21",
    boatClass: "ILCA 6",
    division: "Open",
    totalFleetSize: 11,
    raceCount: 5,
    geography: "SG",
    countsForRanking: true,
    venue: "National Sailing Centre, Singapore",
    organizer: "Singapore Sailing Federation",
    norUrl: "https://www.racingrulesofsailing.org/documents/13596/event",
    registrationUrl: "https://www.sailing.org.sg/events/335514",
    scheduleNotes: "Temasek Regatta 2026 ILCA 6 fleet: 11 entries, 5 races sailed (1 discard).",
  },
  {
    id: "reg-cincapura-2026-ilca-6",
    name: "Cincapura Regatta 2026 (ILCA 6)",
    slug: "cincapura-regatta-2026-ilca-6",
    date: "2026-07-20",
    endDate: "2026-07-21",
    boatClass: "ILCA 6",
    division: "Open",
    totalFleetSize: 16,
    raceCount: 3,
    geography: "SG",
    countsForRanking: true,
    venue: "National Sailing Centre, Singapore",
    organizer: "Singapore Sailing Federation",
    norUrl: "https://www.racingrulesofsailing.org/documents/14587/event",
    registrationUrl: "https://www.sailing.org.sg/events/356060",
    scheduleNotes: "Cincapura Regatta 2026 ILCA 6 fleet: 16 entries, 3 races sailed (no discards).",
  },
  {
    id: "reg-pesta-sukan-2026-ilca-6",
    name: "Pesta Sukan 2026 (ILCA 6)",
    slug: "pesta-sukan-2026-ilca-6",
    date: "2026-08-01",
    endDate: "2026-08-03",
    boatClass: "ILCA 6",
    division: "Open",
    totalFleetSize: 21,
    raceCount: 5,
    geography: "SG",
    countsForRanking: true,
    venue: "National Sailing Centre, Singapore",
    organizer: "Singapore Sailing Federation",
    norUrl: "https://www.racingrulesofsailing.org/documents/14397/event?name=pesta-sukan-2026",
    registrationUrl: "https://www.sailing.org.sg/events/351968",
    scheduleNotes: "Pesta Sukan Regatta 2026 ILCA 6 fleet: 21 entries, 5 races sailed (1 discard).",
  },
  {
    id: "reg-snsc-2026-ilca-6",
    name: "Singapore National Sailing Championships 2026 (ILCA 6)",
    slug: "snsc-ilca-6-sep-26",
    date: "2026-09-11",
    endDate: "2026-09-15",
    boatClass: "ILCA 6",
    division: "Open",
    totalFleetSize: 19,
    raceCount: 9,
    geography: "SG",
    countsForRanking: true,
    venue: "National Sailing Centre, Singapore",
    organizer: "Singapore Sailing Federation",
    norUrl: "https://www.racingrulesofsailing.org/documents/14487/event",
    registrationUrl: "https://www.sailing.org.sg/events/323705",
    scheduleNotes: "Singapore National Sailing Championships 2026 ILCA 6 fleet: 19 entries, 9 races sailed (1 discard).",
  },
];

function slugifyName(name: string): string {
  return name
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-|-$/g, "");
}

export interface PublicRegattaResult {
  resultId: string;
  sailorId: string;
  regattaId: string;
  rank: number;
  nettScore: number;
  totalScore: number;
  isDns: boolean;
  isOverseasCommitment: boolean;
  sailorName: string;
  sailNumber: string;
  handle: string;
  school: string | null;
  club: string | null;
  gender: string | null;
  sailorGender: string | null;
  birthYear: number | null;
  dob: string | null;
  nationality: string | null;
  sailorNationality: string | null;
  verificationStatus: "verified";
  regattaSlug: string;
  regattaName: string;
  raceResults: Array<{
    regattaResultId: string;
    raceNumber: number;
    score: number;
    scoringCode: string | null;
    discarded: boolean;
    rawValue: string;
  }>;
}

export function getStaticIlca6Results(
  regattaIdOrSlug: string
): PublicRegattaResult[] | null {
  const norm = regattaIdOrSlug.toLowerCase();
  let entries: Ilca6CompetitorResult[] | null = null;
  let regatta: RegattaRecord | null = null;

  const directMatch = ILCA6_STATIC_REGATTAS.find(
    (r) => r.id.toLowerCase() === norm || r.slug.toLowerCase() === norm
  );
  if (directMatch) {
    regatta = directMatch;
    if (directMatch.slug.includes("pulau-ujong")) entries = PULAU_UJONG_2026_ILCA6_RESULTS;
    else if (directMatch.slug.includes("sysc")) entries = SYSC_2026_ILCA6_RESULTS;
    else if (directMatch.slug.includes("temasek")) entries = TEMASEK_2026_ILCA6_RESULTS;
    else if (directMatch.slug.includes("cincapura")) entries = CINCAPURA_2026_ILCA6_RESULTS;
    else if (directMatch.slug.includes("pesta")) entries = PESTA_SUKAN_2026_ILCA6_RESULTS;
    else if (directMatch.slug.includes("snsc")) entries = SNSC_2026_ILCA6_RESULTS;
    else if (directMatch.slug.includes("safyc")) entries = SAFYC_2026_ILCA6_RESULTS;
  } else if (norm.includes("pulau-ujong") && (norm.includes("ilca-6") || norm.includes("ilca6"))) {
    entries = PULAU_UJONG_2026_ILCA6_RESULTS;
    regatta = ILCA6_STATIC_REGATTAS[0];
  } else if (norm.includes("sysc") && (norm.includes("ilca-6") || norm.includes("ilca6"))) {
    entries = SYSC_2026_ILCA6_RESULTS;
    regatta = ILCA6_STATIC_REGATTAS[1];
  } else if (norm.includes("temasek") && (norm.includes("ilca-6") || norm.includes("ilca6"))) {
    entries = TEMASEK_2026_ILCA6_RESULTS;
    regatta = ILCA6_STATIC_REGATTAS[2];
  } else if (norm.includes("cincapura") && (norm.includes("ilca-6") || norm.includes("ilca6"))) {
    entries = CINCAPURA_2026_ILCA6_RESULTS;
    regatta = ILCA6_STATIC_REGATTAS[3];
  } else if (norm.includes("pesta") && (norm.includes("ilca-6") || norm.includes("ilca6"))) {
    entries = PESTA_SUKAN_2026_ILCA6_RESULTS;
    regatta = ILCA6_STATIC_REGATTAS[4];
  } else if (norm.includes("snsc") && (norm.includes("ilca-6") || norm.includes("ilca6"))) {
    entries = SNSC_2026_ILCA6_RESULTS;
    regatta = ILCA6_STATIC_REGATTAS[5];
  } else if (norm.includes("safyc") && (norm.includes("ilca-6") || norm.includes("ilca6"))) {
    entries = SAFYC_2026_ILCA6_RESULTS;
    regatta = ILCA6_STATIC_REGATTAS[0];
  }

  if (!entries || !regatta) return null;

  return entries.map((c, i) => {
    const resultId = `${regatta!.id}-res-${i + 1}`;
    const sailorId = `sailor-ilca6-${slugifyName(c.sailorName)}`;
    return {
      resultId,
      sailorId,
      regattaId: regatta!.id,
      rank: c.rank,
      nettScore: c.nettScore,
      totalScore: c.totalScore,
      isDns: c.isDns || false,
      isOverseasCommitment: false,
      sailorName: c.sailorName,
      sailNumber: c.sailNumber,
      handle: slugifyName(c.sailorName),
      school: c.schoolName || null,
      club: c.club || null,
      gender: c.gender,
      sailorGender: c.gender,
      birthYear: c.yearOfBirth || null,
      dob: null,
      nationality: c.nationality || "SGP",
      sailorNationality: c.nationality || "SGP",
      verificationStatus: "verified" as const,
      regattaSlug: regatta!.slug,
      regattaName: regatta!.name,
      raceResults: c.races.map((r) => ({
        regattaResultId: resultId,
        raceNumber: r.raceNumber,
        score: r.score,
        scoringCode: r.scoringCode || null,
        discarded: r.discarded || false,
        rawValue: r.rawValue,
      })),
    };
  });
}

/**
 * Returns sailor, regatta, and result records for ILCA 6 rankings calculation
 * to supplement database rows.
 */
export function getStaticIlca6RankingsData(): {
  sailors: SailorRecord[];
  regattas: RegattaRecord[];
  results: RegattaResultRecord[];
} {
  const regattas = ILCA6_STATIC_REGATTAS;
  const sailorMap = new Map<string, SailorRecord>();
  const results: RegattaResultRecord[] = [];

  const datasets = [
    { regatta: regattas[0], list: PULAU_UJONG_2026_ILCA6_RESULTS },
    { regatta: regattas[1], list: SYSC_2026_ILCA6_RESULTS },
    { regatta: regattas[2], list: TEMASEK_2026_ILCA6_RESULTS },
    { regatta: regattas[3], list: CINCAPURA_2026_ILCA6_RESULTS },
    { regatta: regattas[4], list: PESTA_SUKAN_2026_ILCA6_RESULTS },
    { regatta: regattas[0], list: SAFYC_2026_ILCA6_RESULTS },
    { regatta: regattas[5], list: SNSC_2026_ILCA6_RESULTS },
  ];

  for (const { regatta, list } of datasets) {
    for (const c of list) {
      const id = `sailor-ilca6-${slugifyName(c.sailorName)}`;
      if (!sailorMap.has(id)) {
        sailorMap.set(id, {
          id,
          name: c.sailorName,
          handle: slugifyName(c.sailorName),
          gender: c.gender,
          nationality: c.nationality || "SGP",
          sailNumber: c.sailNumber,
          club: c.club,
          school: c.schoolName,
          ilca6NationalList: true,
          currentFleet: "Series",
          goldEntryDate: null,
          silverEntryDate: null,
          dropDate: null,
        });
      }
      results.push({
        sailorId: id,
        regattaId: regatta.id,
        rank: c.rank,
        nettScore: c.nettScore,
        totalScore: c.totalScore,
        isDns: c.isDns || false,
      });
    }
  }

  return {
    sailors: Array.from(sailorMap.values()),
    regattas,
    results,
  };
}
