import { SailorRecord, RegattaRecord, RegattaResultRecord } from "./ranking";

export interface MockEquipmentLog {
  id: string;
  sailorId: string;
  hullBrand: string;
  sailMake: string;
  foilBrand: string;
}

export const mockSailors: SailorRecord[] = [
  {
    id: "sailor-1",
    name: "Ashlyn Tan",
    handle: "ashlyn-t",
    sailNumber: "SGP 115",
    club: "Changi Sailing Club",
    goldEntryDate: "2025-06-15",
    silverEntryDate: "2024-01-10",
    dropDate: null,
    dob: "2013-08-14",
    weight: 42,
    bio: "Optimist Gold fleet racer passionate about light-wind tactics and local regattas.",
    gender: "F",
    nationalSquadStatus: "Nat A",
    instagram: "@ashlyn.t_sails",
    facebook: null,
    natSquadStatusJan25: "DS",
    natSquadStatusJul25: "Nat B",
    natSquadStatusJan26: "Nat A",
    natSquadStatusJul26: "Nat A",
    histRankingJun24: 15,
    histRankingDec24: 11,
    histRankingJun25: 6,
    histRankingDec25: 4,
    histRankingJun26: 3,
    worlds: 2025,
    european: null,
    asian: 2024,
    seaGames: null,
  },
  {
    id: "sailor-2",
    name: "Bernice Lim",
    handle: "bernice-lim",
    sailNumber: "SGP 99",
    club: "SAFYC Yacht Club",
    goldEntryDate: "2025-07-20",
    silverEntryDate: "2024-02-15",
    dropDate: null,
    dob: "2012-11-03",
    weight: 45,
    bio: "SAFYC racer aiming for the National Squad selection next half-year.",
    gender: "F",
    nationalSquadStatus: "Nat B",
    instagram: "@bernice_lim_sailing",
    facebook: null,
    natSquadStatusJan25: null,
    natSquadStatusJul25: "DS",
    natSquadStatusJan26: "Nat B",
    natSquadStatusJul26: "Nat B",
    histRankingJun24: 28,
    histRankingDec24: 22,
    histRankingJun25: 18,
    histRankingDec25: 12,
    histRankingJun26: 9,
    worlds: null,
    european: 2025,
    asian: null,
    seaGames: null,
  },
  {
    id: "sailor-3",
    name: "Charles Goh",
    handle: "charles-goh",
    sailNumber: "SGP 12",
    club: "National Sailing Center",
    goldEntryDate: "2025-01-01",
    silverEntryDate: "2023-06-10",
    dropDate: null,
    dob: "2011-04-25",
    weight: 48,
    bio: "National training squad member focusing on heavy air boat speed and start tactics.",
    gender: "M",
    nationalSquadStatus: "Nat A",
    instagram: null,
    facebook: "charles.goh.92",
    natSquadStatusJan25: "Nat B",
    natSquadStatusJul25: "Nat A",
    natSquadStatusJan26: "Nat A",
    natSquadStatusJul26: "Nat A",
    histRankingJun24: 8,
    histRankingDec24: 5,
    histRankingJun25: 2,
    histRankingDec25: 2,
    histRankingJun26: 1,
    worlds: 2025,
    european: 2024,
    asian: 2025,
    seaGames: 2025,
  },
  {
    id: "sailor-4",
    name: "Daniel Chia",
    handle: "daniel-chia",
    sailNumber: "SGP 2030",
    club: "Changi Sailing Club",
    goldEntryDate: null,
    silverEntryDate: "2025-01-12",
    dropDate: null,
    dob: "2014-05-18",
    weight: 38,
    bio: "Upcoming Silver fleet competitor learning rules and course geometry.",
    gender: "M",
    nationalSquadStatus: "DS",
    instagram: null,
    facebook: null,
    natSquadStatusJan25: null,
    natSquadStatusJul25: null,
    natSquadStatusJan26: "DS",
    natSquadStatusJul26: "DS",
    histRankingJun24: null,
    histRankingDec24: null,
    histRankingJun25: null,
    histRankingDec25: null,
    histRankingJun26: null,
    worlds: null,
    european: null,
    asian: null,
    seaGames: null,
  },
  {
    id: "sailor-5",
    name: "Ethan Teo",
    handle: "ethan-teo",
    sailNumber: "SGP 88",
    club: "National Sailing Center",
    goldEntryDate: null,
    silverEntryDate: "2025-03-01",
    dropDate: null,
    dob: "2015-02-09",
    weight: 35,
    bio: "Passionate young sailor enjoying weekly training sessions and optimist fleet dynamics.",
    gender: "M",
    nationalSquadStatus: null,
    instagram: null,
    facebook: null,
    natSquadStatusJan25: null,
    natSquadStatusJul25: null,
    natSquadStatusJan26: null,
    natSquadStatusJul26: null,
    histRankingJun24: null,
    histRankingDec24: null,
    histRankingJun25: null,
    histRankingDec25: null,
    histRankingJun26: null,
    worlds: null,
    european: null,
    asian: null,
    seaGames: null,
  },
];

export const mockRegattas: RegattaRecord[] = [
  {
    id: "regatta-1",
    name: "Singapore National Championship 2026",
    slug: "sg-national-championship-2026",
    date: "2026-06-15",
    totalFleetSize: 85,
    division: "Both",
  },
  {
    id: "regatta-2",
    name: "CSC Optimist Championships 2026",
    slug: "csc-optimist-championships-2026",
    date: "2026-05-04",
    totalFleetSize: 60,
    division: "Gold",
  },
  {
    id: "regatta-3",
    name: "SAFYC Regatta 2026",
    slug: "safyc-regatta-2026",
    date: "2026-04-12",
    totalFleetSize: 72,
    division: "Silver",
  },
  {
    id: "regatta-4",
    name: "National Ranking Series 1 2026",
    slug: "national-ranking-series-1-2026",
    date: "2026-02-28",
    totalFleetSize: 90,
    division: "Both",
  },
  {
    id: "regatta-5",
    name: "NSC Cup 2026",
    slug: "nsc-cup-2026",
    date: "2026-01-18",
    totalFleetSize: 55,
    division: "Gold",
  },
];

export const mockRegattaResults: RegattaResultRecord[] = [
  // Ashlyn Tan results
  { sailorId: "sailor-1", regattaId: "regatta-1", rank: 3, nettScore: 24 },
  { sailorId: "sailor-1", regattaId: "regatta-2", rank: 8, nettScore: 68 },
  { sailorId: "sailor-1", regattaId: "regatta-3", rank: 2, nettScore: 18 },
  { sailorId: "sailor-1", regattaId: "regatta-4", rank: 12, nettScore: 95 },
  { sailorId: "sailor-1", regattaId: "regatta-5", rank: 5, nettScore: 32 },

  // Bernice Lim results
  { sailorId: "sailor-2", regattaId: "regatta-1", rank: 11, nettScore: 84 },
  { sailorId: "sailor-2", regattaId: "regatta-2", rank: 4, nettScore: 42 },
  { sailorId: "sailor-2", regattaId: "regatta-3", rank: 15, nettScore: 112 },
  { sailorId: "sailor-2", regattaId: "regatta-4", rank: 6, nettScore: 56 },
  { sailorId: "sailor-2", regattaId: "regatta-5", rank: 9, nettScore: 62 },

  // Charles Goh results
  { sailorId: "sailor-3", regattaId: "regatta-1", rank: 1, nettScore: 12 },
  { sailorId: "sailor-3", regattaId: "regatta-2", rank: 3, nettScore: 31 },
  { sailorId: "sailor-3", regattaId: "regatta-3", rank: 5, nettScore: 38 },
  { sailorId: "sailor-3", regattaId: "regatta-4", rank: 2, nettScore: 21 },
  // DNS on regatta-5 (should score 55 + 1 = 56)

  // Daniel Chia (Silver) results
  { sailorId: "sailor-4", regattaId: "regatta-1", rank: 42, nettScore: 312 },
  { sailorId: "sailor-4", regattaId: "regatta-2", rank: 28, nettScore: 198 },
  { sailorId: "sailor-4", regattaId: "regatta-3", rank: 35, nettScore: 254 },
  // DNS on regatta-4 (91)
  // DNS on regatta-5 (56)

  // Ethan Teo (Silver) results
  { sailorId: "sailor-5", regattaId: "regatta-1", rank: 55, nettScore: 410 },
  { sailorId: "sailor-5", regattaId: "regatta-2", rank: 31, nettScore: 220 },
  { sailorId: "sailor-5", regattaId: "regatta-3", rank: 48, nettScore: 322 },
  { sailorId: "sailor-5", regattaId: "regatta-4", rank: 38, nettScore: 280 },
  // DNS on regatta-5 (56)
];

export const mockEquipmentLogs: MockEquipmentLog[] = [
  {
    id: "eq-1",
    sailorId: "sailor-1",
    hullBrand: "Winner 3D Star",
    sailMake: "J-Sails Classic Blue",
    foilBrand: "DSK Flextra",
  },
  {
    id: "eq-2",
    sailorId: "sailor-2",
    hullBrand: "Carter Boats",
    sailMake: "Olimpic Sails Radial",
    foilBrand: "N1 Foils Carbon",
  },
  {
    id: "eq-3",
    sailorId: "sailor-3",
    hullBrand: "Winner 3D Star",
    sailMake: "J-Sails Classic Red",
    foilBrand: "DSK Flextra",
  },
];

export function getMockData() {
  return {
    sailors: mockSailors,
    regattas: mockRegattas,
    results: mockRegattaResults,
    equipmentLogs: mockEquipmentLogs,
  };
}
