import type { CoachSquadDashboard } from "@/lib/coachDashboard";

export const SAMPLE_COACH_SQUAD_DASHBOARD: CoachSquadDashboard = {
  squad: {
    id: "demo-squad-csc",
    name: "Changi Racing Squad",
  },
  period: {
    year: 2026,
    half: "Jul-Dec",
  },
  updatedThrough: "Singapore National Sailing Championship 2026",
  actionReviews: [],
  members: [
    {
      id: "mem-1",
      sailorId: "sample-kimberly",
      name: "Kimberly Tan",
      handle: "kimberly-t",
      sailNumber: "SGP 115",
      club: "Changi Sailing Club",
      avatarUrl: "/demo-kimberly-tan.jpg",
      fleet: "Gold",
      ranking: 3,
      bestThreeOfFive: 4.0,
      squadStatus: "National Squad A",
      recentMovement: 1,
      scoringEvents: [
        {
          regattaId: "reg-1",
          regattaName: "Singapore National Championship 2026",
          date: "2026-06-20",
          score: 1,
          selected: true,
          isDns: false,
          isOverseas: false,
        },
        {
          regattaId: "reg-2",
          regattaName: "Singapore Youth Sailing Championship 2026",
          date: "2026-03-15",
          score: 2,
          selected: true,
          isDns: false,
          isOverseas: false,
        },
        {
          regattaId: "reg-3",
          regattaName: "CSC Youth Championship 2026",
          date: "2026-01-20",
          score: 1,
          selected: true,
          isDns: false,
          isOverseas: false,
        },
      ],
      recentResults: [
        {
          resultId: "res-1",
          regattaName: "Singapore National Championship 2026",
          regattaSlug: "singapore-national-championship-2026",
          boatClass: "Optimist",
          date: "2026-06-20",
          rank: 1,
          nettScore: 11,
          fleetSize: 64,
          races: [
            { raceNumber: 1, score: 4, code: null, discarded: false, rawValue: "4" },
            { raceNumber: 2, score: 2, code: null, discarded: false, rawValue: "2" },
            { raceNumber: 3, score: 5, code: null, discarded: true, rawValue: "5" },
            { raceNumber: 4, score: 3, code: null, discarded: false, rawValue: "3" },
            { raceNumber: 5, score: 1, code: null, discarded: false, rawValue: "1" },
            { raceNumber: 6, score: 1, code: null, discarded: false, rawValue: "1" },
          ],
        },
      ],
      coachNote: "Mid-line speed on 10s gun was excellent today. Accelerated cleanly without losing height. Focus on downwind wave pumping rhythm for Asian Championship.",
      coachNoteVisibility: "shared",
      developmentRecords: [
        {
          id: "dev-1",
          type: "observation",
          category: "Technical",
          title: "Clean roll-tacks in moderate chop",
          detail: "Consistent mast angle cadence and explosive roll timing on windward shifts.",
          recordDate: "2026-06-21",
          status: "completed",
          targetDate: null,
          visibility: "shared",
          sentiment: "strength",
        },
        {
          id: "dev-2",
          type: "observation",
          category: "Tactical",
          title: "Mid-line start positioning",
          detail: "Held low-speed balance well in 8-10kt breeze. Clear air on acceleration trigger.",
          recordDate: "2026-06-18",
          status: "active",
          targetDate: null,
          visibility: "shared",
          sentiment: "strength",
        },
        {
          id: "dev-3",
          type: "goal",
          category: "Physical",
          title: "Core endurance conditioning",
          detail: "Complete 3x weekly aerobic hiking bench workouts ahead of Perth camp.",
          recordDate: "2026-06-10",
          status: "active",
          targetDate: "2026-08-01",
          visibility: "coach_only",
          sentiment: "focus",
        },
      ],
      selectionReadiness: {
        tone: "ready",
        label: "On track",
        detail: "Rank #3 overall · Qualified for Asian Games Team & Perth Camp roster.",
      },
      latestResult: {
        regattaName: "Singapore National Championship 2026",
        regattaSlug: "singapore-national-championship-2026",
        date: "2026-06-20",
        rank: 1,
        fleetSize: 64,
      },
    },
    {
      id: "mem-2",
      sailorId: "sample-ethan",
      name: "Ethan Koh",
      handle: "ethan-k",
      sailNumber: "SGP 4588",
      club: "Changi Sailing Club",
      avatarUrl: null,
      fleet: "Gold",
      ranking: 7,
      bestThreeOfFive: 11.0,
      squadStatus: "National Squad B",
      recentMovement: -2,
      scoringEvents: [
        {
          regattaId: "reg-1",
          regattaName: "Singapore National Championship 2026",
          date: "2026-06-20",
          score: 8,
          selected: true,
          isDns: false,
          isOverseas: false,
        },
        {
          regattaId: "reg-2",
          regattaName: "Singapore Youth Sailing Championship 2026",
          date: "2026-03-15",
          score: 3,
          selected: true,
          isDns: false,
          isOverseas: false,
        },
      ],
      recentResults: [
        {
          resultId: "res-2",
          regattaName: "Singapore National Championship 2026",
          regattaSlug: "singapore-national-championship-2026",
          boatClass: "Optimist",
          date: "2026-06-20",
          rank: 8,
          nettScore: 24,
          fleetSize: 64,
          races: [],
        },
      ],
      coachNote: "Struggled with port-end crowd congestion in race 3. Need earlier commitment to race line.",
      coachNoteVisibility: "coach_only",
      developmentRecords: [
        {
          id: "dev-4",
          type: "observation",
          category: "Tactical",
          title: "Starting line sag identification",
          detail: "Tended to set up 2-3 lengths behind line; needs to trust bow depth on final 30s.",
          recordDate: "2026-06-19",
          status: "active",
          targetDate: null,
          visibility: "coach_only",
          sentiment: "focus",
        },
      ],
      selectionReadiness: {
        tone: "watch",
        label: "Selection Bubble",
        detail: "Needs 1 more counting event inside top-5 to secure Perth camp nomination.",
      },
      latestResult: {
        regattaName: "Singapore National Championship 2026",
        regattaSlug: "singapore-national-championship-2026",
        date: "2026-06-20",
        rank: 8,
        fleetSize: 64,
      },
    },
    {
      id: "mem-3",
      sailorId: "sample-sarah",
      name: "Sarah Chen",
      handle: "sarah-c",
      sailNumber: "SGP 4701",
      club: "National Sailing Centre",
      avatarUrl: null,
      fleet: "Gold",
      ranking: 11,
      bestThreeOfFive: 14.0,
      squadStatus: "Development",
      recentMovement: 3,
      scoringEvents: [
        {
          regattaId: "reg-1",
          regattaName: "Singapore National Championship 2026",
          date: "2026-06-20",
          score: 4,
          selected: true,
          isDns: false,
          isOverseas: false,
        },
        {
          regattaId: "reg-2",
          regattaName: "Singapore Youth Sailing Championship 2026",
          date: "2026-03-15",
          score: 5,
          selected: true,
          isDns: false,
          isOverseas: false,
        },
        {
          regattaId: "reg-3",
          regattaName: "CSC Youth Championship 2026",
          date: "2026-01-20",
          score: 5,
          selected: true,
          isDns: false,
          isOverseas: false,
        },
      ],
      recentResults: [],
      coachNote: "Excellent progress in upwind VMG. Up 3 places in national ranking series.",
      coachNoteVisibility: "shared",
      developmentRecords: [],
      selectionReadiness: {
        tone: "development",
        label: "Rising Contender",
        detail: "Strong upward momentum. Projected squad promotion if current trend holds.",
      },
      latestResult: {
        regattaName: "Singapore National Championship 2026",
        regattaSlug: "singapore-national-championship-2026",
        date: "2026-06-20",
        rank: 4,
        fleetSize: 64,
      },
    },
    {
      id: "mem-4",
      sailorId: "sample-lucas",
      name: "Lucas Tan",
      handle: "lucas-t",
      sailNumber: "SGP 3108",
      club: "Changi Sailing Club",
      avatarUrl: null,
      fleet: "Silver",
      ranking: 8,
      bestThreeOfFive: 18.0,
      squadStatus: "Silver Squad",
      recentMovement: 0,
      scoringEvents: [
        {
          regattaId: "reg-s1",
          regattaName: "Silver Series Ranking 1",
          date: "2026-05-10",
          score: 6,
          selected: true,
          isDns: false,
          isOverseas: false,
        },
        {
          regattaId: "reg-s2",
          regattaName: "Silver Series Ranking 2",
          date: "2026-04-12",
          score: 5,
          selected: true,
          isDns: false,
          isOverseas: false,
        },
      ],
      recentResults: [],
      coachNote: "Working on boat trim in under 6 knots. Good sprit tension adjustments.",
      coachNoteVisibility: "shared",
      developmentRecords: [],
      selectionReadiness: {
        tone: "development",
        label: "Gold Promotion Target",
        detail: "Top-10 in Silver. Targeting 2027 Gold fleet qualification.",
      },
      latestResult: {
        regattaName: "Silver Series Ranking 1",
        regattaSlug: "silver-series-ranking-1",
        date: "2026-05-10",
        rank: 6,
        fleetSize: 42,
      },
    },
  ],
  following: [
    {
      id: "fol-1",
      sailorId: "sample-marcus",
      name: "Marcus Koh",
      handle: "marcus-k",
      sailNumber: "SGP 2184",
      club: "Changi Sailing Club",
      avatarUrl: null,
      fleet: null,
      ranking: null,
      bestThreeOfFive: null,
      squadStatus: "ILCA 4 Squad",
      recentMovement: null,
      scoringEvents: [],
      recentResults: [],
      coachNote: "Transitioned from Optimist to ILCA 4. Ranked #2 nationally in high points.",
      coachNoteVisibility: "coach_only",
      developmentRecords: [],
      selectionReadiness: {
        tone: "ready",
        label: "ILCA 4 Transition",
        detail: "Active in youth ILCA 4 regattas.",
      },
      latestResult: {
        regattaName: "CSC ILCA Open 2026",
        regattaSlug: "csc-ilca-open-2026",
        date: "2026-07-05",
        rank: 2,
        fleetSize: 28,
      },
    },
  ],
};
