/**
 * Static SAMPLE profile (Ashlyn Tan style) — not from the database.
 * Used only so visitors can visualize a finished sailor profile.
 */
export const SAMPLE_SAILOR = {
  id: "sample-ashlyn",
  name: "Ashlyn Tan",
  handle: "ashlyn-t",
  sailNumber: "SGP 115",
  club: "Changi Sailing Club",
  goldEntryDate: "2025-06-15",
  silverEntryDate: "2024-01-10",
  dropDate: null as string | null,
  currentFleet: "Gold",
  school: "Raffles Institution",
  manuallyDropped: false,
  dob: "2013-08-14",
  weight: 42,
  bio: "Optimist Gold fleet racer passionate about light-wind tactics and local regattas.",
  gender: "F",
  nationalSquadStatus: "Nat A",
  instagram: "@ashlyn.t_sails",
  facebook: null as string | null,
  isPublicWeight: false,
  isPublicDob: false,
  isPublicEquipment: true,
  natSquadStatusJan25: "DS",
  natSquadStatusJul25: "Nat B",
  natSquadStatusJan26: "Nat A",
  natSquadStatusJul26: "Nat A",
  histRankingJun24: 15,
  histRankingDec24: 11,
  histRankingJun25: 6,
  histRankingDec25: 4,
  histRankingJun26: 3,
  worlds: 2025,
  european: null as number | null,
  asian: 2024,
  seaGames: null as number | null,
};

export const SAMPLE_RESULTS = [
  {
    id: "sample-r1",
    regattaId: "sample-r1",
    regattaName: "Singapore National Championship 2026",
    regattaSlug: "sample-nationals-2026",
    regattaDate: "2026-06-15",
    division: "Gold",
    totalFleetSize: 85,
    fleetSize: 85,
    rank: 3,
    nettScore: 24,
  },
  {
    id: "sample-r2",
    regattaId: "sample-r2",
    regattaName: "CSC Optimist Championships 2026",
    regattaSlug: "sample-csc-2026",
    regattaDate: "2026-05-04",
    division: "Gold",
    totalFleetSize: 60,
    fleetSize: 60,
    rank: 8,
    nettScore: 68,
  },
  {
    id: "sample-r3",
    regattaId: "sample-r3",
    regattaName: "SAFYC Regatta 2026",
    regattaSlug: "sample-safyc-2026",
    regattaDate: "2026-04-12",
    division: "Gold",
    totalFleetSize: 72,
    fleetSize: 72,
    rank: 2,
    nettScore: 18,
  },
  {
    id: "sample-r4",
    regattaId: "sample-r4",
    regattaName: "National Ranking Series 1 2026",
    regattaSlug: "sample-nrs1-2026",
    regattaDate: "2026-02-28",
    division: "Gold",
    totalFleetSize: 90,
    fleetSize: 90,
    rank: 12,
    nettScore: 95,
  },
  {
    id: "sample-r5",
    regattaId: "sample-r5",
    regattaName: "NSC Cup 2026",
    regattaSlug: "sample-nsc-2026",
    regattaDate: "2026-01-18",
    division: "Gold",
    totalFleetSize: 55,
    fleetSize: 55,
    rank: 5,
    nettScore: 32,
  },
];

export const SAMPLE_EQUIPMENT = {
  hullBrand: "Winner",
  sailMake: "J-Sails",
  foilBrand: "DSK",
};
