import { z } from "zod";

export const SailorCreateSchema = z.object({
  name: z.string().min(1, "Name is required"),
  handle: z.string().optional(),
  sailNumber: z.string().optional(),
  club: z.string().optional().default("N/A"),
  school: z.string().optional().nullable(),
  gender: z.string().optional().nullable(),
  bio: z.string().optional().nullable(),
  goldEntryDate: z.string().regex(/^\d{4}-\d{2}-\d{2}$/, "Invalid date format (YYYY-MM-DD)").optional().nullable(),
  silverEntryDate: z.string().regex(/^\d{4}-\d{2}-\d{2}$/, "Invalid date format (YYYY-MM-DD)").optional().nullable(),
  dropDate: z.string().regex(/^\d{4}-\d{2}-\d{2}$/, "Invalid date format (YYYY-MM-DD)").optional().nullable(),
  currentFleet: z.string().optional(),
  nationalSquadStatus: z.string().optional().nullable(),
  dob: z.string().regex(/^\d{4}-\d{2}-\d{2}$/, "Invalid date format (YYYY-MM-DD)").optional().nullable(),
  weight: z.preprocess((val) => (val === "" ? null : Number(val)), z.number().optional().nullable()),
  instagram: z.string().optional().nullable(),
  avatarUrl: z.string().url("Invalid URL").optional().nullable(),
  natSquadStatusJan25: z.string().optional().nullable(),
  natSquadStatusJul25: z.string().optional().nullable(),
  natSquadStatusJan26: z.string().optional().nullable(),
  natSquadStatusJul26: z.string().optional().nullable(),
  natSquadStatusJan27: z.string().optional().nullable(),
  natSquadStatusJul27: z.string().optional().nullable(),
  histRankingJun24: z.preprocess((val) => (val === "" ? null : Number(val)), z.number().optional().nullable()),
  histRankingDec24: z.preprocess((val) => (val === "" ? null : Number(val)), z.number().optional().nullable()),
  histRankingJun25: z.preprocess((val) => (val === "" ? null : Number(val)), z.number().optional().nullable()),
  histRankingDec25: z.preprocess((val) => (val === "" ? null : Number(val)), z.number().optional().nullable()),
  histRankingJun26: z.preprocess((val) => (val === "" ? null : Number(val)), z.number().optional().nullable()),
  worlds: z.string().optional().nullable(),
  european: z.string().optional().nullable(),
  asian: z.string().optional().nullable(),
  seaGames: z.string().optional().nullable(),
  sailingJourney: z.string().optional().nullable(),
  nationality: z.string().optional().nullable(),
  sailNumberIlca4: z.string().optional().nullable(),
  boardNumber: z.string().optional().nullable(),
  ilca4NationalList: z.boolean().optional().nullable(),
  ilca6NationalList: z.boolean().optional().nullable(),
  nationalityFromSail: z.boolean().optional().nullable(),
  hullBrand: z.string().optional().nullable(),
  sailMake: z.string().optional().nullable(),
  foilBrand: z.string().optional().nullable(),
  mast: z.string().optional().nullable(),
  equipmentNotes: z.string().optional().nullable(),
  hullBrandIlca4: z.string().optional().nullable(),
  sailMakeIlca4: z.string().optional().nullable(),
  foilBrandIlca4: z.string().optional().nullable(),
  mastIlca4: z.string().optional().nullable(),
  equipmentNotesIlca4: z.string().optional().nullable(),
});

export const SailorPatchSchema = SailorCreateSchema.partial().extend({
  id: z.string().min(1, "ID is required"),
});
