-- Generated by generate-imports.mjs from visually reviewed official PDF source.
-- Import: csc-29er; source: https://drive.google.com/file/d/1LVa-q0PXnBVRqWELr2xVeMVr34A1NUyN/view?usp=drive_link; source title: CSC 29ER Championships 2024.pdf
-- Expected: 4 result rows and 28 individual race scores.
BEGIN;
DO $import$
DECLARE
  payload jsonb := $payload$[{"rank":1,"name":"Seth Low / Amos Tham","handle":"historical-2024-csc-29er-jan-2024-109d74984b68","sail":"SGP","club":"SAFYC","school":null,"gender":"M","nationality":null,"total":9,"nett":7,"duplicateName":false,"races":[[2,null,true],[1,null,false],[2,null,false],[1,null,false],[1,null,false],[1,null,false],[1,null,false]]},{"rank":2,"name":"Nicole Ng Hui Hong / Ezann Sephira Tan","handle":"historical-2024-csc-29er-jan-2024-7e2cc8a29898","sail":"SIN","club":"SAFYC","school":null,"gender":"F","nationality":null,"total":17,"nett":12,"duplicateName":false,"races":[[5,"DSQ",true],[2,null,false],[1,null,false],[3,null,false],[2,null,false],[2,null,false],[2,null,false]]},{"rank":3,"name":"Cheryl Yong Heng Xi / Annika Chui","handle":"historical-2024-csc-29er-jan-2024-3d455a6bbe00","sail":"8","club":"CSC","school":null,"gender":"F","nationality":null,"total":20,"nett":16,"duplicateName":false,"races":[[1,null,false],[3,null,false],[3,null,false],[2,null,false],[4,null,true],[3,null,false],[4,null,false]]},{"rank":4,"name":"Josh Ang Shaal","handle":"historical-2024-csc-29er-jan-2024-19a995d5ebbe","sail":"153","club":null,"school":null,"gender":"M","nationality":null,"total":27,"nett":22,"duplicateName":false,"races":[[5,"DNS",true],[4,null,false],[4,null,false],[4,null,false],[3,null,false],[4,null,false],[3,null,false]]}]$payload$::jsonb;
  v_event uuid;
  v_regatta uuid;
  v_sailor uuid;
  v_result uuid;
  v_candidate_count integer;
  v_expected_results integer := 4;
  v_expected_races integer := 7;
  item jsonb;
  race jsonb;
  race_no integer;
BEGIN
  PERFORM pg_advisory_xact_lock(hashtext('official-2024-csc-29er-jan-2024'));
  SELECT id INTO v_event FROM public.regatta_events WHERE slug = 'csc-ilca-29er-championships-2024';
  IF v_event IS NULL THEN RAISE EXCEPTION 'Missing parent event: %', 'csc-ilca-29er-championships-2024'; END IF;

  INSERT INTO public.regattas (
    name, slug, event_id, date, end_date, total_fleet_size, division, race_count,
    geography, boat_class, counts_for_ranking, venue, organizer, schedule_notes, status, reviewed_at
  ) VALUES (
    'CSC ILCA & 29er Championships 2024 (29er)', 'csc-29er-jan-2024', v_event, DATE '2024-01-13', DATE '2024-01-14',
    4, 'Open', 7, 'SGP', '29er', false,
    'Changi Sailing Club, Singapore', 'Changi Sailing Club', 'Official provisional results, visually reviewed. Best 6 of 7 races count. Two-person boats are retained as historical team-entry profiles.', 'published', now()
  ) ON CONFLICT (slug) DO UPDATE SET
    name = EXCLUDED.name, event_id = EXCLUDED.event_id, date = EXCLUDED.date, end_date = EXCLUDED.end_date,
    total_fleet_size = EXCLUDED.total_fleet_size, division = EXCLUDED.division, race_count = EXCLUDED.race_count,
    geography = EXCLUDED.geography, boat_class = EXCLUDED.boat_class, counts_for_ranking = EXCLUDED.counts_for_ranking,
    venue = EXCLUDED.venue, organizer = EXCLUDED.organizer, schedule_notes = EXCLUDED.schedule_notes,
    status = 'published', reviewed_at = now(), updated_at = now()
  RETURNING id INTO v_regatta;

  FOR item IN SELECT value FROM jsonb_array_elements(payload) LOOP
    SELECT count(DISTINCT s.id), min(s.id::text)::uuid INTO v_candidate_count, v_sailor
    FROM public.sailors s
    LEFT JOIN public.sailor_aliases a ON a.sailor_id = s.id
    WHERE (lower(trim(COALESCE(s.name, ''))) = lower(trim(item->>'name')) OR lower(trim(COALESCE(a.alias_name, ''))) = lower(trim(item->>'name')))
      AND (COALESCE((item->>'duplicateName')::boolean, false) = false OR (lower(trim(COALESCE(s.sail_number, ''))) = lower(trim(COALESCE(item->>'sail', ''))) OR lower(trim(COALESCE(s.sail_number_ilca4, ''))) = lower(trim(COALESCE(item->>'sail', '')))));

    IF v_candidate_count > 1 THEN
      RAISE EXCEPTION 'Ambiguous SailorPath identity for % (% candidates)', item->>'name', v_candidate_count;
    ELSIF v_candidate_count = 0 THEN
      INSERT INTO public.sailors (name, handle, sail_number, club, school, gender, nationality, created_at, updated_at)
      VALUES (item->>'name', item->>'handle', COALESCE(NULLIF(item->>'sail', ''), '0'), COALESCE(NULLIF(item->>'club', ''), 'N/A'), NULLIF(item->>'school', ''), NULLIF(item->>'gender', ''), NULLIF(item->>'nationality', ''), now(), now())
      ON CONFLICT (handle) DO UPDATE SET updated_at = now()
      RETURNING id INTO v_sailor;
    END IF;

    INSERT INTO public.regatta_results (
      sailor_id, regatta_id, rank, nett_score, total_score, gender, nationality,
      evidence_url, evidence_name, evidence_type, official_url, evidence_notes,
      verification_status, verified_at
    ) VALUES (
      v_sailor, v_regatta, (item->>'rank')::integer, (item->>'nett')::real, (item->>'total')::real,
      NULLIF(item->>'gender', ''), NULLIF(item->>'nationality', ''), 'https://drive.google.com/file/d/1LVa-q0PXnBVRqWELr2xVeMVr34A1NUyN/view?usp=drive_link', 'CSC 29ER Championships 2024.pdf', 'link', 'https://drive.google.com/file/d/1LVa-q0PXnBVRqWELr2xVeMVr34A1NUyN/view?usp=drive_link',
      'Official source name: ' || (item->>'name') || '; historical sail/board number: ' || COALESCE(NULLIF((item->>'sail'), ''), 'not supplied') ||
      '; club at event: ' || COALESCE(NULLIF((item->>'club'), ''), 'not listed') || '. PDF table rendered and visually verified before import.',
      'verified', now()
    ) ON CONFLICT (sailor_id, regatta_id) DO UPDATE SET
      rank = EXCLUDED.rank, nett_score = EXCLUDED.nett_score, total_score = EXCLUDED.total_score,
      gender = EXCLUDED.gender, nationality = EXCLUDED.nationality, evidence_url = EXCLUDED.evidence_url,
      evidence_name = EXCLUDED.evidence_name, evidence_type = EXCLUDED.evidence_type, official_url = EXCLUDED.official_url,
      evidence_notes = EXCLUDED.evidence_notes, verification_status = 'verified', verified_at = now(), updated_at = now()
    RETURNING id INTO v_result;

    race_no := 0;
    FOR race IN SELECT value FROM jsonb_array_elements(item->'races') LOOP
      race_no := race_no + 1;
      INSERT INTO public.regatta_race_results (regatta_result_id, race_number, score, scoring_code, discarded, raw_value)
      VALUES (
        v_result, race_no, (race->>0)::real, race->>1, (race->>2)::boolean,
        CASE WHEN race->>1 IS NULL THEN CASE WHEN (race->>2)::boolean THEN '(' || (race->>0) || ')' ELSE race->>0 END
             ELSE CASE WHEN (race->>2)::boolean THEN '(' || (race->>1) || ',' || (race->>0) || ')' ELSE (race->>1) || ',' || (race->>0) END END
      ) ON CONFLICT (regatta_result_id, race_number) DO UPDATE SET
        score = EXCLUDED.score, scoring_code = EXCLUDED.scoring_code, discarded = EXCLUDED.discarded,
        raw_value = EXCLUDED.raw_value, updated_at = now();
    END LOOP;
    DELETE FROM public.regatta_race_results WHERE regatta_result_id = v_result AND race_number > race_no;

    IF race_no <> v_expected_races
       OR (SELECT sum(score) FROM public.regatta_race_results WHERE regatta_result_id = v_result) <> (item->>'total')::real
       OR (SELECT sum(score) FROM public.regatta_race_results WHERE regatta_result_id = v_result AND NOT discarded) <> (item->>'nett')::real THEN
      RAISE EXCEPTION 'Individual race-score validation failed for %', item->>'name';
    END IF;
  END LOOP;

  IF (SELECT count(*) FROM public.regatta_results WHERE regatta_id = v_regatta) <> v_expected_results THEN
    RAISE EXCEPTION 'Unexpected result count for csc-29er-jan-2024';
  END IF;
  IF (SELECT count(*) FROM public.regatta_race_results race JOIN public.regatta_results result ON result.id = race.regatta_result_id WHERE result.regatta_id = v_regatta) <> v_expected_results * v_expected_races THEN
    RAISE EXCEPTION 'Unexpected race-score count for csc-29er-jan-2024';
  END IF;
END
$import$;
COMMIT;

SELECT r.slug, count(DISTINCT rr.id)::int AS result_count, count(race.id)::int AS race_score_count,
       bool_and(rr.total_score = scores.total_score AND rr.nett_score = scores.nett_score) AS scores_reconcile
FROM public.regattas r
LEFT JOIN public.regatta_results rr ON rr.regatta_id = r.id
LEFT JOIN public.regatta_race_results race ON race.regatta_result_id = rr.id
LEFT JOIN LATERAL (
  SELECT sum(score)::real AS total_score, sum(score) FILTER (WHERE NOT discarded)::real AS nett_score
  FROM public.regatta_race_results
  WHERE regatta_result_id = rr.id
) scores ON true
WHERE r.slug = 'csc-29er-jan-2024'
GROUP BY r.slug
LIMIT 1;
