/**
 * 2026 Singapore & International Youth Sailing Regatta Calendar
 *
 * Official and key youth regattas across Optimist, ILCA 4, ILCA 6, and WingFoil.
 * Includes Notice of Race (NOR), registration links, venues, selection designations,
 * international campaigns, and Singapore travel/campaign budget estimates.
 */

export type CampaignBudgetBreakdown = {
  totalEstimatedSgd: number;
  regattaCostsLabel: string;
  clinicLabel?: string;
  flightsLabel?: string;
  lodgingLabel?: string;
  notes?: string;
};

export type CalendarActionDeadline = {
  date: string; // YYYY-MM-DD
  label: string;
  eventSlug: string;
  region: "Singapore" | "Asia" | "Europe" | "International";
  urgent?: boolean;
};

export type RegattaCalendarEntry = {
  name: string;
  slug: string;
  startDate: string; // YYYY-MM-DD
  endDate?: string;  // YYYY-MM-DD
  boatClass: string; // e.g. "Optimist", "ILCA 4", "ILCA 6", "WingFoil", "All"
  /** Classes sailed at this regatta. Shown instead of a single boat-class chip. */
  classes?: string[];
  division: string;  // e.g. "National", "Gold", "Silver", "Open"
  venue: string;     // e.g. "National Sailing Centre"
  region: "Singapore" | "Asia" | "Europe" | "International";
  geography?: string;
  organizer: string; // e.g. "Singapore Sailing Federation"
  countsForRanking: boolean;
  isSelectionTrial: boolean;
  norUrl?: string | null;
  registrationUrl?: string | null;
  scheduleNotes?: string | null;
  totalFleetSize: number;
  targetFleet?: string;
  keyDeadlines?: string;
  clinicDates?: string;
  prizesSummary?: string | null;
  campaignBudget?: CampaignBudgetBreakdown;
};

export const CALENDAR_ACTION_DEADLINES: CalendarActionDeadline[] = [
  {
    date: "2026-10-01",
    label: "Charter reservation deadline for Eastern Seaboard Regatta (RVYC allocations are limited)",
    eventSlug: "eastern-seaboard-regatta-2026",
    region: "Asia",
    urgent: true,
  },
  {
    date: "2026-10-10",
    label: "Early bird entry closes for Trofeo Torboli (Lake Garda)",
    eventSlug: "8th-autumn-meeting-48th-trofeo-torboli-2026",
    region: "Europe",
  },
  {
    date: "2026-10-31",
    label: "Final registration & charter payment deadline for 2026 IODA Asians (Colombo)",
    eventSlug: "2026-optimist-asian-oceania-championship",
    region: "Asia",
  },
  {
    date: "2026-11-01",
    label: "Online entry opens for Torrevieja Euromarina Trophy (00:00 CET, 450 boat cap; sells out rapidly)",
    eventSlug: "xix-euromarina-optimist-trophy-2027",
    region: "Europe",
  },
  {
    date: "2026-12-15",
    label: "Boat charter cutoff for Palamós International Trophy",
    eventSlug: "37th-international-palamos-optimist-trophy-2027",
    region: "Europe",
  },
  {
    date: "2026-12-31",
    label: "Early bird registration discount cutoff for Hong Kong Race Week 2027",
    eventSlug: "hong-kong-race-week-2027",
    region: "Asia",
  },
];

export const SINGAPORE_REGATTAS_2026: RegattaCalendarEntry[] = [
  {
    name: "HKRW Optimist Selection Trials 2026",
    slug: "hkrw-optimist-selection-trials-2026",
    startDate: "2026-01-10",
    endDate: "2026-01-11",
    boatClass: "Optimist",
    division: "National",
    region: "Singapore",
    geography: "SG",
    venue: "National Sailing Centre, East Coast",
    organizer: "Singapore Sailing Federation",
    countsForRanking: true,
    isSelectionTrial: true,
    targetFleet: "Optimist Ranking Fleet",
    norUrl: "https://www.racingrulesofsailing.org/documents/170680",
    scheduleNotes: "Official selection trials for Hong Kong Race Week squad.",
    totalFleetSize: 65,
  },
  {
    name: "Pulau Ujong Regatta 2026",
    slug: "pulau-ujong-regatta-2026",
    startDate: "2026-02-28",
    endDate: "2026-03-01",
    boatClass: "Optimist",
    division: "Open",
    region: "Singapore",
    geography: "SG",
    venue: "Changi Sailing Club",
    organizer: "Changi Sailing Club",
    countsForRanking: true,
    isSelectionTrial: false,
    targetFleet: "Open Fleet",
    norUrl: "https://www.racingrulesofsailing.org/documents/13180/event",
    scheduleNotes: "Annual Pulau Ujong offshore & fleet racing weekend.",
    totalFleetSize: 75,
  },
  {
    name: "22nd SAFYC Regatta 2026",
    slug: "22nd-safyc-regatta-2026",
    startDate: "2026-03-28",
    endDate: "2026-03-29",
    boatClass: "Optimist",
    division: "Gold / Silver",
    region: "Singapore",
    geography: "SG",
    venue: "SAF Yacht Club, Sembawang",
    organizer: "SAF Yacht Club",
    countsForRanking: true,
    isSelectionTrial: false,
    targetFleet: "Gold & Silver Fleets",
    norUrl: "https://www.racingrulesofsailing.org/documents/13551/event",
    scheduleNotes: "22nd edition of the SAFYC annual dinghy regatta.",
    totalFleetSize: 85,
  },
  {
    name: "Temasek Regatta 2026",
    slug: "temasek-regatta-2026",
    startDate: "2026-06-20",
    endDate: "2026-06-21",
    boatClass: "Optimist",
    classes: ["Optimist", "ILCA 4", "ILCA 6", "ILCA 7", "29er", "Techno 293", "iQFOiL", "WingFoil"],
    division: "Gold / Silver",
    region: "Singapore",
    geography: "SG",
    venue: "National Sailing Centre, 1500 East Coast Parkway",
    organizer: "Singapore Sailing Federation",
    countsForRanking: true,
    isSelectionTrial: false,
    targetFleet: "Optimist, ILCA, 29er, and boards",
    norUrl: "https://www.racingrulesofsailing.org/documents/13596/event",
    registrationUrl: "https://www.sailing.org.sg/events/335514",
    keyDeadlines: "Entry closes 7 June 2026, 2359h. Entry fee by 17 May 2026, 2359h.",
    scheduleNotes:
      "Amendment 2 (15 June 2026). 20–21 June at NSC. Gold, ILCA, and 29er: 6 races, max 4/day. Silver: 5 races, max 3/day. Techno 293: 8 races, max 5/day. iQFOiL and WingFoil: 10 races, max 5/day.",
    totalFleetSize: 198,
  },
  {
    name: "Singapore Youth Sailing Championships 2026",
    slug: "singapore-youth-sailing-championships-2026",
    startDate: "2026-06-20",
    endDate: "2026-06-23",
    boatClass: "Optimist",
    division: "National",
    region: "Singapore",
    geography: "SG",
    venue: "National Sailing Centre, East Coast",
    organizer: "Singapore Sailing Federation",
    countsForRanking: true,
    isSelectionTrial: true,
    targetFleet: "Gold & Silver Fleets",
    norUrl: "https://www.racingrulesofsailing.org/documents/178539",
    scheduleNotes: "Official Selection Trial #1 for Optimist Asian Games & Perth Camp squad. 4 days of fleet racing.",
    totalFleetSize: 110,
  },
  {
    name: "Singapore Youth Sailing Championships 2026 (ILCA 4)",
    slug: "singapore-youth-sailing-championships-2026-ilca4",
    startDate: "2026-06-20",
    endDate: "2026-06-23",
    boatClass: "ILCA 4",
    division: "National",
    region: "Singapore",
    geography: "SG",
    venue: "National Sailing Centre, East Coast",
    organizer: "Singapore Sailing Federation",
    countsForRanking: true,
    isSelectionTrial: true,
    targetFleet: "ILCA 4 Youth Fleet",
    norUrl: "https://www.racingrulesofsailing.org/documents/178539",
    scheduleNotes: "National ranking series scoring event for ILCA 4 youth fleet.",
    totalFleetSize: 45,
  },
  {
    name: "2nd SAFYC Optimist Championships 2026",
    slug: "2nd-safyc-optimist-championships-2026",
    startDate: "2026-07-04",
    endDate: "2026-07-05",
    boatClass: "Optimist",
    classes: ["Optimist"],
    division: "Gold / Silver",
    region: "Singapore",
    geography: "SG",
    venue: "NSRCC Seasports Centre, 11 Changi Coast Walk",
    organizer: "SAF Yacht Club",
    countsForRanking: true,
    isSelectionTrial: false,
    targetFleet: "Optimist Gold and Silver",
    norUrl: "https://www.racingrulesofsailing.org/documents/14691/event",
    registrationUrl: "https://www.safyc.org.sg",
    keyDeadlines: "Entry closes 25 June 2026. Early bird on or before 25 June.",
    scheduleNotes:
      "Optimist Gold and Silver only. First warning 1100h on 4 and 5 July. Prize presentation 1800h on 5 July. Official results final 6 July 2026: Gold 7 races, 1 discard, 91 entries; Silver 5 races, 1 discard, 58 entries.",
    totalFleetSize: 149,
  },
  {
    name: "Changi Sailing Club Youth Championship 2026",
    slug: "csc-youth-championship-2026",
    startDate: "2026-07-18",
    endDate: "2026-07-19",
    boatClass: "Optimist",
    division: "Gold / Silver",
    region: "Singapore",
    geography: "SG",
    venue: "Changi Sailing Club",
    organizer: "Changi Sailing Club",
    countsForRanking: true,
    isSelectionTrial: false,
    targetFleet: "Gold & Silver Fleets",
    scheduleNotes: "Changi waters tidal racing. 6 races scheduled over 2 days.",
    totalFleetSize: 85,
  },
  {
    name: "Cincapura Regatta 2026",
    slug: "cincapura-regatta-2026",
    startDate: "2026-07-20",
    endDate: "2026-07-21",
    boatClass: "Optimist",
    classes: ["Optimist", "ILCA 4", "ILCA 6", "ILCA 7", "29er", "Techno 293", "iQFOiL", "WingFoil"],
    division: "Gold / Silver",
    region: "Singapore",
    geography: "SG",
    venue: "National Sailing Centre, Singapore",
    organizer: "Singapore Sailing Federation",
    countsForRanking: true,
    isSelectionTrial: false,
    targetFleet: "Gold & Silver Fleets",
    norUrl: "https://www.racingrulesofsailing.org/documents/14587/event",
    registrationUrl: "https://www.sailing.org.sg/events/356060",
    scheduleNotes:
      "Cincapura Regatta 2026 held at National Sailing Centre. Optimist Gold Fleet: 86 competitors, 3 races sailed (no discards). Optimist Silver Fleet: 55 competitors, 4 races sailed (1 discard).",
    prizesSummary:
      "Gold Fleet: Open (1st-10th), Female (1st-3rd), 11-12yo (1st-5th), 9-10yo (1st-5th). Silver Fleet: Open (1st-10th), Female (1st-3rd), 8&U (1st-3rd), Novice (1st-5th), 9-10yo (1st-3rd).",
    totalFleetSize: 141,
  },
  {
    name: "Pesta Sukan Regatta 2026 (Optimist)",
    slug: "pesta-sukan-regatta-2026-optimist",
    startDate: "2026-07-25",
    endDate: "2026-08-02",
    boatClass: "Optimist",
    classes: ["Optimist", "ILCA 4", "ILCA 6", "ILCA 7", "29er", "Techno 293", "iQFOiL", "WingFoil"],
    division: "Gold / Silver",
    region: "Singapore",
    geography: "SG",
    venue: "National Sailing Centre, East Coast",
    organizer: "Singapore Sailing Federation",
    countsForRanking: true,
    isSelectionTrial: false,
    targetFleet: "Gold & Silver Fleets",
    norUrl: "https://www.racingrulesofsailing.org/documents/14397/event?name=pesta-sukan-2026",
    registrationUrl: "https://www.sailing.org.sg/events/351968",
    keyDeadlines: "Entry closes 13 July 2026, 2359h (Early bird: 6 July)",
    scheduleNotes: "2-weekend festival at NSC. W1 (25-26 Jul): Optimist Silver (5 races scheduled, max 3/day) & Open Water Festival Passage Race (25 Jul 1300h). W2 (1-2 Aug): Optimist Gold (6 races scheduled, max 4/day). Early bird: $78 (Single) / $156 (Double).",
    prizesSummary: "Gold Fleet: Open 1st-10th, Female 1st-3rd, Age 11-12 1st-5th, Age 9-10 1st-5th, Primary/Sec School 1st. Silver Fleet: Open 1st-10th, Female 1st-3rd, Age 9-10 1st-3rd, 8&U 1st-3rd, Novice 1st-10th, Primary School 1st.",
    totalFleetSize: 120,
  },
  {
    name: "Pesta Sukan Regatta 2026 (ILCA & WingFoil)",
    slug: "pesta-sukan-regatta-2026-ilca-wingfoil",
    startDate: "2026-07-25",
    endDate: "2026-08-02",
    boatClass: "ILCA 4",
    classes: ["Optimist", "ILCA 4", "ILCA 6", "ILCA 7", "29er", "Techno 293", "iQFOiL", "WingFoil"],
    division: "National",
    region: "Singapore",
    geography: "SG",
    venue: "National Sailing Centre, East Coast",
    organizer: "Singapore Sailing Federation",
    countsForRanking: true,
    isSelectionTrial: false,
    targetFleet: "ILCA 4, ILCA 6, ILCA 7, 29er & Boards",
    norUrl: "https://www.racingrulesofsailing.org/documents/14397/event?name=pesta-sukan-2026",
    registrationUrl: "https://www.sailing.org.sg/events/351968",
    keyDeadlines: "Entry closes 13 July 2026, 2359h (Early bird: 6 July)",
    scheduleNotes: "W1 (25-26 Jul): Boards (Techno 293/293+, iQFOiL, WingFoil - 7 races scheduled, max 5/day) & Open Water Passage Race. W2 (1-2 Aug): ILCA 4, ILCA 6, ILCA 7, 29er (6 races scheduled, max 4/day). Early bird: $78.",
    prizesSummary: "ILCA 4: Open 1st-3rd, Female 1st-3rd, Novice 1st-3rd, 13&U 1st-3rd, Sec School 1st. ILCA 6: Open 1st-3rd, Female 1st-3rd, Novice 1st-3rd, 15&U 1st-3rd, Sec/JC/Poly 1st. WingFoil & iQFOiL: 18&U 1st-3rd, Female 1st. Passage Race: 1st-3rd all classes.",
    totalFleetSize: 60,
  },
  {
    name: "2026 SSF Selection Trials",
    slug: "ssf-selection-trials-2026",
    startDate: "2026-08-22",
    endDate: "2026-08-30",
    boatClass: "Optimist",
    division: "Gold",
    region: "Singapore",
    geography: "SG",
    venue: "National Sailing Centre, East Coast",
    organizer: "Singapore Sailing Federation",
    countsForRanking: true,
    isSelectionTrial: true,
    targetFleet: "National Selection Squad",
    norUrl: "https://www.racingrulesofsailing.org/documents/200930",
    scheduleNotes: "High-intensity multi-weekend trials. Combined scores determine Asian Games & Perth Camp national squads.",
    totalFleetSize: 70,
  },
  {
    name: "Singapore National Sailing Championships 2026",
    slug: "singapore-national-sailing-championships-2026",
    startDate: "2026-09-05",
    endDate: "2026-09-13",
    boatClass: "Optimist",
    classes: ["Optimist", "ILCA 4", "ILCA 6", "ILCA 7", "29er", "Techno 293", "WingFoil"],
    division: "National",
    region: "Singapore",
    geography: "SG",
    venue: "National Sailing Centre, East Coast",
    organizer: "Singapore Sailing Federation",
    countsForRanking: true,
    isSelectionTrial: true,
    targetFleet: "National Championships Fleet",
    norUrl: "https://www.racingrulesofsailing.org/documents/14487/event",
    registrationUrl: "https://www.sailing.org.sg/events/323705",
    keyDeadlines: "Entry closes 24 August 2026, 2359h (Early bird: 17 August)",
    scheduleNotes: "Singapore National Sailing Championships across 2 weekends at NSC. W1 (5-7 Sep): Optimist Silver (7 races scheduled, max 3/day), Boards / WingFoil / Techno (12 races scheduled, max 5/day). W2 (11-13 Sep): Optimist Gold (9 races scheduled, max 4/day), ILCA 4, ILCA 6, ILCA 7, 29er (9 races scheduled, max 4/day). Early bird: $117 (Single) / $234 (Double).",
    prizesSummary: "Gold Fleet: Open 1st-10th, Female 1st-3rd, Age 11-12 1st-5th, Age 9-10 1st-5th, Primary/Sec School 1st. Silver Fleet: Open 1st-10th, Female 1st-3rd, Age 9-10 1st-3rd, 8&U 1st-3rd, Novice 1st-10th, Primary School 1st.",
    totalFleetSize: 130,
  },
  {
    name: "2026 Optimist European Team Racing Championship",
    slug: "2026-optimist-european-team-racing-championship",
    startDate: "2026-10-13",
    endDate: "2026-10-18",
    boatClass: "Optimist",
    division: "Team Racing",
    region: "Europe",
    geography: "IT",
    venue: "Campione del Garda, Italy",
    organizer: "IODA / Univela Sailing",
    countsForRanking: false,
    isSelectionTrial: false,
    targetFleet: "National Team Selections (U16)",
    keyDeadlines: "Registration closes late Sept 2026",
    norUrl: "https://www.optiworld.org/default/events/ioda?ini=1",
    registrationUrl: "https://www.optiworld.org/default/events/ioda?ini=1",
    scheduleNotes: "Premier European youth team racing championship on Lake Garda. Invitation-only for qualified national delegations.",
    totalFleetSize: 64,
  },
  {
    name: "8th Autumn Meeting & 48th Trofeo Torboli",
    slug: "8th-autumn-meeting-48th-trofeo-torboli-2026",
    startDate: "2026-10-23",
    endDate: "2026-10-25",
    boatClass: "Optimist",
    division: "Open",
    region: "Europe",
    geography: "IT",
    venue: "Fraglia Vela Riva, Riva del Garda, Italy",
    organizer: "Fraglia Vela Riva",
    countsForRanking: false,
    isSelectionTrial: false,
    targetFleet: "Juniores & Cadetti (Open)",
    keyDeadlines: "Early bird entry Oct 10, 2026",
    norUrl: "https://fragliavelariva.it/regate/a2226187-e2ea-419a-a3f9-fb4f66570d47",
    registrationUrl: "https://fragliavelariva.it/regate/a2226187-e2ea-419a-a3f9-fb4f66570d47",
    scheduleNotes: "Iconic Lake Garda autumn youth regatta with over 350 junior sailors. Exceptional tactical cliff-line racing.",
    totalFleetSize: 350,
  },
  {
    name: "Eastern Seaboard Regatta 2026 & Pre-Event Clinic",
    slug: "eastern-seaboard-regatta-2026",
    startDate: "2026-10-29",
    endDate: "2026-10-31",
    boatClass: "Optimist",
    division: "Open / Green",
    region: "Asia",
    geography: "TH",
    venue: "Royal Varuna Yacht Club (RVYC), Pattaya, Thailand",
    organizer: "Royal Varuna Yacht Club",
    countsForRanking: false,
    isSelectionTrial: false,
    targetFleet: "Open & Green Fleet",
    keyDeadlines: "Charter cutoff Oct 1; Entry closes Oct 15",
    clinicDates: "Clinic Oct 26–28, 2026",
    norUrl: "https://www.optiworld.org/default/events/event/text/eastern-seaboard-regatta/page/0",
    registrationUrl: "https://www.optiworld.org/default/events/event/text/eastern-seaboard-regatta/page/0",
    scheduleNotes: "6-day campaign (3-day high-performance clinic + 3-day regatta). RVYC warm coastal waters with steady breezes and moderate chop.",
    totalFleetSize: 120,
    campaignBudget: {
      totalEstimatedSgd: 2736,
      regattaCostsLabel: "THB 22,000 (~SGD 836) — Entry THB 6k, Charter THB 12k, Coach/RIB pool THB 4k",
      clinicLabel: "THB 14,000 (~SGD 532) — 3-day high-performance training clinic",
      flightsLabel: "SGD 608 — Scoot nonstop return for 2 pax (SIN–BKK)",
      lodgingLabel: "THB 20,000 (~SGD 760) — 6 nights near RVYC + private airport van transfers",
      notes: "Calculated for 1 youth sailor + 1 accompanying adult from Singapore.",
    },
  },
  {
    name: "2026 Optimist Asian & Oceanian Championship",
    slug: "2026-optimist-asian-oceania-championship",
    startDate: "2026-12-12",
    endDate: "2026-12-19",
    boatClass: "Optimist",
    division: "International",
    region: "Asia",
    geography: "LK",
    venue: "Colombo Port City, Sri Lanka",
    organizer: "IODA / Yachting Association of Sri Lanka",
    countsForRanking: false,
    isSelectionTrial: false,
    targetFleet: "National Squads (Fleet & Team Race)",
    keyDeadlines: "Final registration & charter payment deadline Oct 31, 2026",
    clinicDates: "Wave tuning clinic Dec 10–11, 2026",
    norUrl: "https://www.optiworld.org/default/events/event/text/2026-optimist-asian-oceanian-championship",
    registrationUrl: "https://www.optiworld.org/default/events/event/text/2026-optimist-asian-oceanian-championship",
    scheduleNotes: "Official overseas campaign for Singapore National Team (Top 10 qualified + reserves). 2-day pre-event wave and current tuning camp.",
    totalFleetSize: 160,
    campaignBudget: {
      totalEstimatedSgd: 5310,
      regattaCostsLabel: "USD 1,150 (~SGD 1,457) — IODA Entry USD 450, Charter USD 550, Coach/RIB pool USD 150",
      clinicLabel: "USD 500 (~SGD 634) — 2-day pre-event ocean tuning clinic",
      flightsLabel: "SGD 1,698 — AirAsia return for 2 pax (SIN–CMB)",
      lodgingLabel: "USD 1,200 (~SGD 1,521) — Official event hotel 9 nights + shuttle",
      notes: "Calculated for 1 youth sailor + 1 accompanying adult from Singapore.",
    },
  },
  {
    name: "XIX Euromarina Optimist Trophy & Winter Clinic",
    slug: "xix-euromarina-optimist-trophy-2027",
    startDate: "2027-01-20",
    endDate: "2027-01-24",
    boatClass: "Optimist",
    division: "International",
    region: "Europe",
    geography: "ES",
    venue: "Real Club Náutico Torrevieja (RCNT), Torrevieja, Spain",
    organizer: "Real Club Náutico Torrevieja / AECIO",
    countsForRanking: false,
    isSelectionTrial: false,
    targetFleet: "Sub-16 & Sub-13 (Excellence Cup)",
    keyDeadlines: "Registration opens Nov 1, 2026 (00:00 CET; 450 boat cap)",
    clinicDates: "Winter clinic Jan 16–19, 2027",
    norUrl: "https://www.optiworld.org/default/events?year=2026&month=0",
    registrationUrl: "https://www.optiworld.org/default/events?year=2026&month=0",
    scheduleNotes: "9-day campaign (4-day winter clinic + 4-day Optimist Excellence Cup). Elite European fleet capped at 450 sailors.",
    totalFleetSize: 450,
    campaignBudget: {
      totalEstimatedSgd: 7418,
      regattaCostsLabel: "EUR 1,050 (~SGD 1,544) — Entry €180, Charter €550, Safety tag €40, Coach/RIB share €280",
      clinicLabel: "EUR 550 (~SGD 809) — 4-day winter racing camp",
      flightsLabel: "SGD 3,300 — Return flights for 2 pax (SIN–ALC/MAD)",
      lodgingLabel: "EUR 1,200 (~SGD 1,765) — Seaside apartment 9 nights €850 + car rental and fuel €350",
      notes: "Calculated for 1 youth sailor + 1 accompanying adult from Singapore.",
    },
  },
  {
    name: "37th International Palamós Optimist Trophy & Nations Cup",
    slug: "37th-international-palamos-optimist-trophy-2027",
    startDate: "2027-02-11",
    endDate: "2027-02-15",
    boatClass: "Optimist",
    division: "International",
    region: "Europe",
    geography: "ES",
    venue: "Club de Vela Palamós, Costa Brava, Spain",
    organizer: "Club de Vela Palamós / CV Costa Brava",
    countsForRanking: false,
    isSelectionTrial: false,
    targetFleet: "Sub-16 & Sub-13 (550+ sailors)",
    keyDeadlines: "Charter cutoff Dec 15, 2026; Entry closes Jan 15, 2027",
    clinicDates: "Pre-regatta camp Feb 6–10, 2027",
    norUrl: "https://www.optiworld.org/default/events/event/text/36-international-palamos-optimist-trophy",
    registrationUrl: "https://www.optiworld.org/default/events/event/text/36-international-palamos-optimist-trophy",
    scheduleNotes: "10-day campaign (5-day pre-regatta clinic + 4-day International Trophy). Premier European winter regatta with 550+ sailors from 30+ nations.",
    totalFleetSize: 550,
    campaignBudget: {
      totalEstimatedSgd: 7883,
      regattaCostsLabel: "EUR 1,150 (~SGD 1,691) — Entry €195, Charter €600, Measurement €45, Coach/RIB share €310",
      clinicLabel: "EUR 650 (~SGD 956) — 5-day pre-regatta clinic",
      flightsLabel: "SGD 3,250 — Return flights for 2 pax (SIN–BCN)",
      lodgingLabel: "EUR 1,350 (~SGD 1,986) — 10 nights lodging €950 + car rental & tolls €400",
      notes: "Calculated for 1 youth sailor + 1 accompanying adult from Singapore.",
    },
  },
  {
    name: "Hong Kong Race Week 2027 (ASAF Youth Cup)",
    slug: "hong-kong-race-week-2027",
    startDate: "2027-02-16",
    endDate: "2027-02-21",
    boatClass: "Optimist",
    division: "International",
    region: "Asia",
    geography: "HK",
    venue: "Middle Island & Repulse Bay, Hong Kong",
    organizer: "Hong Kong Sailing Federation / RHKYC",
    countsForRanking: false,
    isSelectionTrial: false,
    targetFleet: "Main Fleet (Gold/Silver) & Green",
    keyDeadlines: "Early bird Dec 31, 2026; Registration closes Jan 25, 2027",
    clinicDates: "Southside tactical clinic Feb 13–15, 2027",
    norUrl: "https://www.hkoda.org/events",
    registrationUrl: "https://www.hkoda.org/events",
    scheduleNotes: "8-day campaign (3-day Southside tactical clinic + 4-day ASAF Youth Cup). Competitive international fleet in Hong Kong waters.",
    totalFleetSize: 180,
    campaignBudget: {
      totalEstimatedSgd: 4667,
      regattaCostsLabel: "HKD 7,200 (~SGD 1,174) — Entry HKD 2.2k, Charter HKD 3.8k, Coach/RIB pool HKD 1.2k",
      clinicLabel: "HKD 3,800 (~SGD 619) — 3-day Southside tactical clinic",
      flightsLabel: "SGD 1,000 — Singapore Airlines nonstop for 2 pax (SIN–HKG)",
      lodgingLabel: "HKD 11,500 (~SGD 1,874) — Aberdeen/Wong Chuk Hang hotel 7 nights HKD 10k + transit HKD 1.5k",
      notes: "Calculated for 1 youth sailor + 1 accompanying adult from Singapore.",
    },
  },
];
